### ISSUE TITLE
3-bit quantization fails during the packing stage

### ISSUE THREAD

**Issue by zoidbb** [qwopqwop200/GPTQ-for-LLaMa#1]
```
Packing ...
model.decoder.layers.0.self_attn.q_proj
Traceback (most recent call last):
  File "/root/convert/GPTQ-for-LLaMa/llama.py", line 420, in <module>
    llama_pack3(model, quantizers)
  File "/root/convert/GPTQ-for-LLaMa/llama.py", line 216, in llama_pack3
    qlayers[name].pack(layers[name], quantizers[name].scale, quantizers[name].zero)
  File "/root/convert/GPTQ-for-LLaMa/quant.py", line 142, in pack
    self.bias = linear.bias.clone()
AttributeError: 'NoneType' object has no attribute 'clone'
```

**Comment by zoidbb** [comment]
this impacts both 4-bit and 3-bit quantization

**Comment by zoidbb** [comment]
I was able to fix this by removing line 142 from file quant.py, which sets self.bias. self.bias isn't even used in that function, so this line is unnecessary, and bias is None on pretty much every layer for this model.

**Comment by qwopqwop200** [comment]
i solved it.

**Comment by Yardanico** [comment]
@qwopqwop200 sorry for pinging you here, but I just wanted to ask - how much VRAM would a 3-bit version of LLAMA-30B require (e.g. can it run on 16GB VRAM), and would it be fast enough (like at least a few tokens per second) on e.g. RTX A4000?

**Comment by qwopqwop200** [comment]
If you do 3-bit quantization, it seems to consume about 14gb of memory at 30B. The inference rate is expected to be less than 0.1s/token.

**Comment by Yardanico** [comment]
@qwopqwop200 wow, thanks for all of your efforts, that's amazing! I can tolerate accuracy loss as it'll still be much better than 4-bit LLAMA 13b.
