### ISSUE TITLE
Change ints to double in quant_cuda_kernel.cu?

### ISSUE THREAD

**Issue by xiscoding** [qwopqwop200/GPTQ-for-LLaMa#10]
I was getting this error when running python setup_cuda.py

quant_cuda_kernel.cu(149):` error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)
          detected during instantiation of "void VecQuant2MatMulKernel(const scalar_t *, const int *, scalar_t *, const scalar_t *, const scalar_t *, int, int, int, int) [with scalar_t=double]" 
(87): here

quant_cuda_kernel.cu(261): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)
          detected during instantiation of "void VecQuant3MatMulKernel(const scalar_t *, const int *, scalar_t *, const scalar_t *, const scalar_t *, int, int, int, int) [with scalar_t=double]" 
(171): here

quant_cuda_kernel.cu(337): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)
          detected during instantiation of "void VecQuant4MatMulKernel(const scalar_t *, const int *, scalar_t *, const scalar_t *, const scalar_t *, int, int, int, int) [with scalar_t=double]" 
(283): here

quant_cuda_kernel.cu(409): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)
          detected during instantiation of "void VecQuant8MatMulKernel(const scalar_t *, const int *, scalar_t *, const scalar_t *, const scalar_t *, int, int, int, int) [with scalar_t=double]" 
(359): here

SO I changed all the integers to doubles... and it compiled with a bunch of warnings... Is this defeating the point or is this a valid solution?
Nothing runs atm so I guess not.

**Comment by xiscoding** [comment]
I can not find torch/all.h or torch/python.h my fault

**Comment by qwopqwop200** [comment]
Unable to reproduce this error.
Have you installed pytorch by any chance?

**Comment by xiscoding** [comment]
I installed it through cuda for python... not sure if that matters, sorry I am going through the instructions on this https://pytorch.org/cppdocs/installing.html page and maybe that will help. I did not have cmake or anything.

**Comment by xiscoding** [comment]
Ya that link is not going to help. I just need to find the torch/all.h and torch/python.h files and put the full path in the include. Do you know where those files are? They are not in the same location where torch is installed.

**Comment by antegral** [comment]
```sh
$ find / -name all.h
/opt/conda/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/all.h
/opt/conda/lib/python3.9/site-packages/torch/include/ATen/ops/all.h
/opt/conda/pkgs/pytorch-1.13.1-py3.9_cuda11.7_cudnn8.5.0_0/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/all.h
/opt/conda/pkgs/pytorch-1.13.1-py3.9_cuda11.7_cudnn8.5.0_0/lib/python3.9/site-packages/torch/include/ATen/ops/all.h
```

```sh
$ find / -name python.h
/opt/conda/lib/python3.9/site-packages/debugpy/_vendored/pydevd/pydevd_attach_to_process/common/python.h
/opt/conda/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/python.h
/opt/conda/pkgs/pytorch-1.13.1-py3.9_cuda11.7_cudnn8.5.0_0/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/python.h
```

```sh
$ find / -name cuda.h
/opt/conda/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/cuda.h
/opt/conda/include/cuda.h
/opt/conda/pkgs/pytorch-1.13.1-py3.9_cuda11.7_cudnn8.5.0_0/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/cuda.h
/opt/conda/pkgs/cuda-cudart-dev-11.7.99-0/include/cuda.h
```

```sh
$ find / -name cuda_runtime.h
/opt/conda/include/cuda_runtime.h
/opt/conda/pkgs/cuda-cudart-dev-11.7.99-0/include/cuda_runtime.h
```

**Comment by xiscoding** [comment]
unfortunately I got this far and it did nothing... This error looks like it might be the cause
`
/home/xdoestech/anaconda3/envs/textgen/bin/nvcc -I/home/xdoestech/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/include -I/home/xdoestech/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/xdoestech/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/include/TH -I/home/xdoestech/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/include/THC -I/home/xdoestech/anaconda3/envs/textgen/include -I/home/xdoestech/anaconda3/envs/textgen/include/python3.10 -c quant_cuda_kernel.cu -o build/temp.linux-x86_64-cpython-310/quant_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=quant_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
`
This part specifically: 
-D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ 

Did you get past it?

**Comment by xiscoding** [comment]
Holy cow I am a fool I forgot to set visible devices... 
I have a 960 that does not support 8bit quantization...

`CUDA_DEVICE_ORDER="PCI_BUS_ID" CUDA_VISIBLE_DEVICES="0,2" python setup_cuda.py install`

set the visible devices to the devices that are supported by 8bit
