### ISSUE TITLE
conda activate textgen - при активации среды, выходит эта ошибка.

### ISSUE THREAD

**Issue by EvgenProgromist** [qwopqwop200/GPTQ-for-LLaMa#103]
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\fddgfergergergergergegr\lib\site-packages\conda\exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "D:\fddgfergergergergergegr\lib\site-packages\conda\cli\main.py", line 94, in main_sourced
        print(activator.execute(), end="")
      File "D:\fddgfergergergergergegr\lib\encodings\cp1251.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u253c' in position 618: character maps to <undefined>

`$ D:\fddgfergergergergergegr\Scripts\conda-script.py shell.powershell activate textgen`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=D:\fddgfergergergergergegr\Scripts\conda.exe
             CONDA_PREFIX=D:\fddgfergergergergergegr
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=D:\fddgfergergergergergegr\python.exe
               CONDA_ROOT=D:\fddgfergergergergergegr
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\Евгений
               LD_PRELOAD=<not set>
                     PATH=D:\fddgfergergergergergegr;D:\fddgfergergergergergegr\Library\mingw-
                          w64\bin;D:\fddgfergergergergergegr\Library\usr\bin;D:\fddgfergergerger
                          gergegr\Library\bin;D:\fddgfergergergergergegr\Scripts;D:\fddgfergerge
                          rgergergegr\bin;D:\fddgfergergergergergegr\condabin;C:\WINDOWS\system3
                          2;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPower
                          Shell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\NVIDIA
                          Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Users\┼тухэшщ\App
                          Data\Local\Microsoft\WindowsApps;C:\Users\┼тухэшщ\AppData\Local\GitHub
                          Desktop\bin
             PSMODULEPATH=C:\Users\Евгений\OneDrive\Документы\WindowsPowerShell\Modules;C:\Progr
                          am Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShe
                          ll\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : D:\fddgfergergergergergegr
            shell level : 1
       user config file : C:\Users\Евгений\.condarc
 populated config files :
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=11.6=0
                          __win=0=0
       base environment : D:\fddgfergergergergergegr  (writable)
      conda av data dir : D:\fddgfergergergergergegr\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\fddgfergergergergergegr\pkgs
                          C:\Users\Евгений\.conda\pkgs
                          C:\Users\B7E3~1\AppData\Local\conda\conda\pkgs
       envs directories : D:\fddgfergergergergergegr\envs
                          C:\Users\Евгений\.conda\envs
                          C:\Users\B7E3~1\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.10.9 Windows/10 Windows/10.0.22621
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

**Comment by mityarko** [comment]
Try to avoid Cyrillic characters in your Windows username
