### ISSUE TITLE
the quantnized model can not run with error, when set inference batch_size=4、8、16

### ISSUE THREAD

**Issue by lileilai** [qwopqwop200/GPTQ-for-LLaMa#109]
Thanks for your method for the quantized of llama, and when i try this code, i have face some problem. when i modify the code to support batch generate, such as batch_size=4

```
python3 llama_inference.py /data1/llama-7b/ --wbits 4 --load llama7b-4bit.pt --text "My name is Julien and I like to make" --max_length 128
```
the llama_inference.py was changed as follows:
```
tokenizer = AutoTokenizer.from_pretrained(args.model)

    text = [args.text] * 16

    for idx, bs in enumerate([4]):
        t0 = time.time()
        input_ids = tokenizer.batch_encode_plus(text[ :bs], return_tensors="pt").input_ids.to(DEV)
        # print(input_ids)
        with torch.no_grad():
            generated_ids = model.generate(
                input_ids,
                do_sample=True,
                min_length=args.min_length,
                max_length=args.max_length,
                top_p=args.top_p,
                temperature=args.temperature,
            )
        torch.cuda.synchronize()
        time_consume = time.time() - t0
        print(f"consume  time: {time_consume*1000:.2f} ms")

        print(tokenizer.batch_decode(generated_ids))
        torch.cuda.empty_cache()
        gc.collect()
```
i have face the error
![image](https://user-images.githubusercontent.com/25097411/229090561-c00bc28a-6664-493d-a4f3-cada1afb8a77.png)

**Comment by qwopqwop200** [comment]
Changed to use Triton instead of CUDA now. It seems that this problem won't happen.

**Comment by lileilai** [comment]
> Changed to use Triton instead of CUDA now. It seems that this problem won't happen.

After i run the new code from your repo, the error still occurs occasionally。 And the speed is slower 10x than pytorch in fp16

![image](https://user-images.githubusercontent.com/25097411/229337444-612c3b5a-9d15-4c93-ad05-53cc8e73a11f.png)

**Comment by qwopqwop200** [comment]
Your measurement seems wrong.
Change your code to the following and test.
```
    model.to(DEV)
    tokenizer = AutoTokenizer.from_pretrained(args.model)
    text = [args.text] * 64

    for idx, bs in enumerate([4,4,4,4]):
        t0 = time.time()
        input_ids = tokenizer.batch_encode_plus(text[ :bs], return_tensors="pt").input_ids.to(DEV)
        # print(input_ids)
        with torch.no_grad():
            generated_ids = model.generate(
                input_ids,
                do_sample=True,
                min_length=args.min_length,
                max_length=args.max_length,
                top_p=args.top_p,
                temperature=args.temperature,
            )
        torch.cuda.synchronize()
        time_consume = time.time() - t0
        print(f"consume  time: {time_consume*1000:.2f} ms")

        print(tokenizer.batch_decode(generated_ids))
        torch.cuda.empty_cache()
        gc.collect()
```
Since the first batch consumes a lot of time due to triton, it is correct to compare from the second batch.

batch 4 result: 50 token / ms  
cuda: 1688.47ms
triton: 2437.59ms

**Comment by lileilai** [comment]
> Your measurement seems wrong. Change your code to the following and test.
> 
> ```
>     model.to(DEV)
>     tokenizer = AutoTokenizer.from_pretrained(args.model)
>     text = [args.text] * 64
> 
>     for idx, bs in enumerate([4,4,4,4]):
>         t0 = time.time()
>         input_ids = tokenizer.batch_encode_plus(text[ :bs], return_tensors="pt").input_ids.to(DEV)
>         # print(input_ids)
>         with torch.no_grad():
>             generated_ids = model.generate(
>                 input_ids,
>                 do_sample=True,
>                 min_length=args.min_length,
>                 max_length=args.max_length,
>                 top_p=args.top_p,
>                 temperature=args.temperature,
>             )
>         torch.cuda.synchronize()
>         time_consume = time.time() - t0
>         print(f"consume  time: {time_consume*1000:.2f} ms")
> 
>         print(tokenizer.batch_decode(generated_ids))
>         torch.cuda.empty_cache()
>         gc.collect()
> ```
> 
> Since the first batch consumes a lot of time due to triton, it is correct to compare from the second batch.
> 

> batch 4 result: 50 token / ms cuda: 1688.47ms triton: 2437.59ms

Thanks for your reply !
I change my code , my GPU is 3090Ti, max_length=128
and my result:

triton: 5927.86 ms

In addition, the error as follows occurs occationally

![image](https://user-images.githubusercontent.com/25097411/229351173-8c616339-20b3-4859-9c19-5e3990502f0d.png)
