### ISSUE TITLE
Error with 8-bit unpacking, kernel switch threshold ignored

### ISSUE THREAD

**Issue by QM60** [qwopqwop200/GPTQ-for-LLaMa#111]
It seems there is an issue with 8bit past the kernel switch threshold (128). 8bit quants will emit garbage if the initial context is past 128 tokens.
To prove it is an issue with unpacking, the following hack fixes the problem! The bug must be in the unpack for 8bit. This is on cuda branch.
```
diff --git a/quant.py b/quant.py
index aa63d86..c3c0c89 100644
--- a/quant.py
+++ b/quant.py
@@ -304,7 +304,7 @@ class QuantLinear(nn.Module):
             else:
                 self.bias = None

-        if not self.kernel_switch_threshold is None and (x.shape[0] * x.shape[1]) >= self.kernel_switch_threshold:
+        if self.bits < 8 and not self.kernel_switch_threshold is None and (x.shape[0] * x.shape[1]) >= self.kernel_switch_threshold:
             if self.bits == 2:
                 # Unpack 2bit weights
```

Extra note: passing kernel_switch_threshold=None to make_quant does NOT fix it.  Only this code change. So there is also another bug, something in between must be forgetting to pass this parameter.

**Comment by qwopqwop200** [comment]
fix it.
probably won't cause any problems
