### ISSUE TITLE
some cuda error when inference

### ISSUE THREAD

**Issue by cuimingle** [qwopqwop200/GPTQ-for-LLaMa#114]
CUDA_VISIBLE_DEVICES=0 python llama_inference.py ../0321_shards/ --wbits 8 --groupsize 128 --load llama7b-8bit-128g.pt --text "this is llama"
Loading model ...
Done.
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'LlaMATokenizer'. 
The class this function is called from is 'LlamaTokenizer'.
/usr/bin/ld: skipping incompatible /usr/lib/libcuda.so when searching for -lcuda
/usr/bin/ld: skipping incompatible /usr/lib/libcuda.so when searching for -lcuda
/usr/bin/ld: skipping incompatible /usr/lib/libcuda.so when searching for -lcuda
/usr/bin/ld: skipping incompatible /usr/lib/libcuda.so when searching for -lcuda

**Comment by qwopqwop200** [comment]
Do not use huggingface checkpoints converted to older versions of Transformers.
