### ISSUE TITLE
Is setup_cuda.py missing from the triton branch on purpose?

### ISSUE THREAD

**Issue by JohnGageanu** [qwopqwop200/GPTQ-for-LLaMa#115]

**Comment by qwopqwop200** [comment]
Yes. Removed on purpose for simplicity of code.

**Comment by YellowRoseCx** [comment]
> Yes. Removed on purpose for simplicity of code.

May I ask why you made the triton branch the default one when it's so much slower than your normal cuda branch? I regularly get 1/10th to 1/20th the speed with triton compared to cuda on Linux with 6800xt

**Comment by qwopqwop200** [comment]
Triton is slow on first run due to optimizations and then about twice as fast as cuda.
