### ISSUE TITLE
alternative plan for triton on windows

### ISSUE THREAD

**Issue by loveaguai** [qwopqwop200/GPTQ-for-LLaMa#116]
could someone used an alternative plan to replace the triton package in windows

**Comment by jllllll** [comment]
Your only option at the moment is to use the cuda branch or WSL2. I got pretty close to getting triton to compile on Windows. Unfortunately, I don't know enough about CMAKE to make it work. There was a commit back in February that made changes to allow it to compile, but that build may be too old to work with this.

**Comment by whynothackme** [comment]
> 有人可以使用替代计划来替换 Windows 中的 triton 包吗

The CUDA version works well on Windows (without using WSL2). What is the reason for caching Triton? Is it for higher performance?

**Comment by whynothackme** [comment]
> could someone used an alternative plan to replace the triton package in windows

The CUDA version works well on Windows (without using WSL2). What is the reason for caching Triton? Is it for higher performance?

**Comment by qwopqwop200** [comment]
> > could someone used an alternative plan to replace the triton package in windows
> 
> The CUDA version works well on Windows (without using WSL2). What is the reason for caching Triton? Is it for higher performance?

yes
