### ISSUE TITLE
state_dict error on model load

### ISSUE THREAD

**Issue by GamerUntouch** [qwopqwop200/GPTQ-for-LLaMa#12]
Currently using https://huggingface.co/decapoda-research/llama-13b-hf for the .config file and https://huggingface.co/decapoda-research/llama-13b-hf-int4 for the actual model file.

On load, following the readme, I get this error.

Missing key(s) in state_dict: "model.decoder.embed_tokens.weight", "model.decoder.layers.0.self_attn.q_proj.zeros", "model.decoder.layers.0.self_attn.q_proj.scales",  **etc...**

Using transformers Version: 4.27.0.dev0
Using torch Version: 1.13.1
Using datasets Version: 2.10.1
and on CUDA release 11.7

Everything as far as I can tell has been set up properly, with the kernel compiling working.

EDIT:
After downgrading to 1.12.1, I'm being told 3060 doesn't work with the version of pytorch. It's still giving me the error, though.

EDIT 2: Going to downgrade CUDA to 11.3 to see if it does anything.

**Comment by LoopControl** [comment]
Found the problem -- the pt file was out of date. I downloaded the updated version from https://huggingface.co/decapoda-research/llama-7b-hf-int4/ and it works!
