### ISSUE TITLE
Request for multi-gpu inference

### ISSUE THREAD

**Issue by GenTxt** [qwopqwop200/GPTQ-for-LLaMa#121]
Everything working well with RTX3090 and llama-30b-4bit models. Thanks for the great repo.

Have tried modifying to run on 2 gpus so llama-65b-4bit will load on both without OOM but no luck.

Currently only solution is to load via text-generation-webui. 

Is it possible to have the same multi-gpu inference option in GPTQ-for-LLaMa for both cuda and triton branches?

Cheers,

**Comment by qwopqwop200** [comment]
There are no plans to support. The main reason is that I don't have a GPU to test this on.
