### ISSUE TITLE
TypeError: '<' not supported between instances of 'tuple' and 'float'

### ISSUE THREAD

**Issue by johnrobinsn** [qwopqwop200/GPTQ-for-LLaMa#129]
I'm not able to get past this error...   I saw similar closed issues that suggested reconverting the weights to ht transformer format... I tried reconverting the model weights to HF format... (I even tried the huggyllama/* transformer weights but no luck)

Here are the commands that I used... 

# reconverted to HF transformer format
python convert_llama_weights_to_hf.py --input_dir /mnt/llama_weights/LLaMA/ --model_size 7B --output_dir ./llama-hf

# quantize
CUDA_VISIBLE_DEVICES=0 python llama.py ./llama-hf/llama-7b c4 --wbits 4 --true-sequential --act-order --groupsize 128 --save llama7b-4bit-128g.pt

# load/test
CUDA_VISIBLE_DEVICES=0 python llama.py ./llama-hf/llama-7b c4 --wbits 4 --groupsize 128 --load llama7b-4bit-128g.pt --benchmark 2048 --check

Gives me this error... 

Traceback (most recent call last):                                                            
  File "/mnt2/code/gptq_llama_2/llama.py", line 443, in <module>                              
    model = load_quant(args.model, args.load, args.wbits, args.groupsize)                     
  File "/mnt2/code/gptq_llama_2/llama.py", line 265, in load_quant                            
    autotune_warmup(model)                                                                    
  File "/mnt2/code/gptq_llama_2/quant.py", line 359, in autotune_warmup                       
    QuantLinearFunction.apply(a, qweight.cuda(), scales.cuda(), qzeros.cuda(), g_idx.cuda(), bits, maxq)
  File "/home/jr/anaconda3/envs/gptq_llama_2/lib/python3.9/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/jr/anaconda3/envs/gptq_llama_2/lib/python3.9/site-packages/torch/cuda/amp/autocast_mode.py", line 106, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/mnt2/code/gptq_llama_2/quant.py", line 367, in forward
    matmul_248_kernel[grid](input, qweight, output,
  File "/mnt2/code/gptq_llama_2/custom_autotune.py", line 93, in run
    self.cache[key] = builtins.min(timings, key=timings.get)
TypeError: '<' not supported between instances of 'tuple' and 'float'

**Comment by luxtiasco** [comment]
https://github.com/openai/triton/pull/1208

**Comment by rohvani** [comment]
Also running into this. @luxtiasco, It looks like the PR was merged into triton, and should be included in triton 2.0.0, but yet this error still occurs with triton 2.0.0 installed for me.

**Comment by luxtiasco** [comment]
> Also running into this. @luxtiasco, It looks like the PR was merged into triton, and should be included in triton 2.0.0, but yet this error still occurs with triton 2.0.0 installed for me.

Build 2.1.0 and it works with the not 

> Also running into this. @luxtiasco, It looks like the PR was merged into triton, and should be included in triton 2.0.0, but yet this error still occurs with triton 2.0.0 installed for me.

Build 2.1.0 latest, and use the trition branch but a version before the commit that introduces custom_autotune.py

**Comment by ghost** [comment]
I have the same error when running the t5 benchmark

**Comment by brendan-donohoe** [comment]
In case it helps, I run into the error when using a 16 GB T4 GPU with a newly quantized 7B 4bit and 13B 4bit Llama model (each with 128 group size). When swapping out to a 40 GB A100, I experience no errors with any of the former quantized models nor with a 30B 4bit group size 32 or 128 model.  The T4 works fine in the aforementioned cases with the Cuda branch, but not the Triton branch.

**Comment by fmac2000** [comment]
> [openai/triton#1208](https://github.com/openai/triton/pull/1208)

This fixed the issue for me:

custom_autotune.py
line 71 `		return triton.testing.do_bench(kernel_call, percentiles=(0.5, 0.2, 0.8), rep=40)`
line 72 `	except triton.compiler.OutOfResources:`
line 73 `		return (float('inf'), float('inf'), float('inf'))`

**Comment by brendan-donohoe** [comment]
> > [openai/triton#1208](https://github.com/openai/triton/pull/1208)
> 
> This fixed the issue for me:
> 
> custom_autotune.py line 71 ` return triton.testing.do_bench(kernel_call, percentiles=(0.5, 0.2, 0.8), rep=40)` line 72 ` except triton.compiler.OutOfResources:` line 73 ` return (float('inf'), float('inf'), float('inf'))`

Can confirm that this takes care of the issue on my end as well.

**Comment by luxtiasco** [comment]
Or you should use triton 2.1, not 2.0 from pypi...

**Comment by johnrobinsn** [comment]
Thanks much for the help... 

Closing

**Comment by brendan-donohoe** [comment]
@fmac2000 Would you be willing to make a pull request to merge this fix to `custom_autotune.py`? Seems like a quick and harmless fix that'll curb these errors for the time being.

**Comment by luxtiasco** [comment]
> 

Better with latest triton build from git. Pypi version 2.0 has other problems.

**Comment by fmac2000** [comment]
> > 
> 
> Better with latest triton build from git. Pypi version 2.0 has other problems.

I personally had more issues trying to build triton from source than this small tweak.


> @fmac2000 Would you be willing to make a pull request to merge this fix to `custom_autotune.py`? Seems like a quick and harmless fix that'll curb these errors for the time being.

@johnrobinsn made a commit, thank you 👍
