### ISSUE TITLE
Model Quantization Instructions

### ISSUE THREAD

**Issue by MarkSchmidty** [qwopqwop200/GPTQ-for-LLaMa#13]
How does someone produce a quantized model (e.g. 4bit) themselves?
What are the steps?

**Comment by qwopqwop200** [comment]
If you are talking about model quantization other than OPT, BLOOM, and LLaMa,
See https://github.com/IST-DASLab/gptq/issues/3.

**Comment by MarkSchmidty** [comment]
Just LLaMA.

I found this:
```
python llama.py C:\Users\lxe\text-generation-webui\models\llama-7b c4 --wbits 4 --save llama-7b-4bit.pt
```

But it's unclear to me. Is the input for this script the original .pth format model from Facebook or the HuggingFace format model?

**Comment by qwopqwop200** [comment]
This requires a HuggingFace format model.
