### ISSUE TITLE
Suggestion: Split Cuda and Triton into their own packages OR Merge them into one

### ISSUE THREAD

**Issue by da3dsoul** [qwopqwop200/GPTQ-for-LLaMa#132]
Also, fix the breaking changes and allow loading older models.
One of the biggest issues of the past 2 months is that everything is moving too fast, and a model from literally 2 weeks ago doesn't work anymore.
To simplify dependency resolution and allow running multiple models from various sources via text-generation-webui, separating the packages would allow running both side by side and switching between them as needed. The breaking changes are just really aggravating, and from what I could tell from reading, rather unnecessary.
I would be willing to help, but it's ultimately your decision.

**Comment by da3dsoul** [comment]
I think it may be possible to merge the packages instead, based on what I'm looking at in the code so far. If someone can help explain, I'd be grateful.
Does triton require kernel patches, like the cuda branch does?

From what I can tell, the only dependency differences are the inclusion of triton, which is still in the cuda branch anyway. I expect that was just a mistake.

The ultimate goal of this was to avoid breaking changes to the API in the future. Merging the two branches and allowing the user/developer to simply use `load_quant(*args, **kwargs)` and handling the changes, deprecation, etc in a validation step in load_quant seems like the best move. kwargs is one way to do it. Only ever adding parameters, and adding them with defaults is another way.

**Comment by qwopqwop200** [comment]
The biggest reason for splitting the Triton right now is the simplicity of the code. Actually the only difference between cuda and triton is quant.py and cuda.
