### ISSUE TITLE
Does triton branch support using multiple gpus?

### ISSUE THREAD

**Issue by sgsdxzy** [qwopqwop200/GPTQ-for-LLaMa#135]
I can get smaller triton quantized models to run, but the Llama-65b model cannot fit into a single gpu.
I used to get the cuda version to load on multiple gpus, it works almost transparently. However for the triton branch, the models loads, but at inference stage it fails with `expecting tensors on the same device, found 'cuda:0' and 'cuda:1'`
So does the triton branch not support multiple gpu, or needs special treatment?

**Comment by qwopqwop200** [comment]
I think it can support multiple GPUs, but unfortunately I don't have an extra GPU to test this with.

**Comment by Roooxu** [comment]
> I can get smaller triton quantized models to run, but the Llama-65b model cannot fit into a single gpu. I used to get the cuda version to load on multiple gpus, it works almost transparently. However for the triton branch, the models loads, but at inference stage it fails with `expecting tensors on the same device, found 'cuda:0' and 'cuda:1'` So does the triton branch not support multiple gpu, or needs special treatment?

Try this:
max_memory_mapping = {0: "20GB", 1: "20GB"}
model = AutoModelForCausalLM.from_pretrained(
    base_path, 
    device_map='auto', 
    low_cpu_mem_usage=True,
    torch_dtype=torch.float16, 
    max_memory=max_memory_mapping
)
tokenizer.encode("Your prompt", return_tensors="pt").cuda()

model.generate(input_ids=batch).cuda()

**Comment by sgsdxzy** [comment]
@Roooxu I think this will load the model in fp16?

**Comment by Roooxu** [comment]
> 

Sorry this is my first comment on github etc.
Idk your case but you can get this error : expecting tensors on the same device, found 'cuda:0' and 'cuda:1' from trying to compute model on different devices soo for all of my casses with this error this what i said is propably ok.
You want to split model to memory of your gpus but (i think) you cant compute on both in one time soo this will setup your env to compute on 1 gpu and share memory on 2.

Before i raw pasted example from my code.
You need to focus on this:

import os
os.environ['CUDA_VISIBLE_DEVICES'] = '1'

max_memory_mapping = {0: "XXXXXXGB", 1: "XXXXXXGB"} # change XXXXXX to your max free GB on each gpu

model = AutoModelForCausalLM.from_pretrained(
base_path, 
device_map='auto', # add this
max_memory=max_memory_mapping # add this
)

tokenizer.encode("Your prompt", return_tensors="pt").cuda() # .cuda() is key part

model.generate(input_ids=batch).cuda() # .cuda() is key part
