### ISSUE TITLE
the version of transformers,sentenpiece and tokenizers

### ISSUE THREAD

**Issue by Ji-Cather** [qwopqwop200/GPTQ-for-LLaMa#136]
Thank you very much for the wonderful project. but when i was trying to run the 30B model, I had some problem with the versions of python packages.

I have done the quantization of 30B model with 

python llama.py $QUANTIZE_ORI_PATH c4 --wbits 4 --true-sequential --act-order --groupsize 128 --save $QUANTIZE_DST_PATH/llama30b-4bit-128g.pt 

but when I was trying to do inference with 

python llama_inference.py $QUANTIZE_ORI_PATH --wbits 4 --groupsize 128 --load $QUANTIZE_DST_PATH/llama30b-4bit-128g.pt --text "tell me something about the meaning and functions of AI"

This error appears
![image](https://user-images.githubusercontent.com/68957284/230540891-00431b7a-e002-4113-b9ef-0275cf983bea.png)

So I was trying to upgrade the version of tokenizers, and I upgrade it to v0.13.3 with the whl file from https://pypi.org/project/tokenizers/#files.
but then this error appears:
![image](https://user-images.githubusercontent.com/68957284/230441741-ccdd9450-51d4-4dc0-9038-2efa03febcb9.png)

Someone says it's bacause of the mismatching of sentencepiece and transformers. transformers: 4.28.0.dev0 sentencepiece :0.1.97.
I tried to delete and re-download them, but it didn't seem to work.

**Comment by s4rduk4r** [comment]
I had the same issue and solved it by creating a new conda environment. Try this recipe, probably it'll solve your issue:
```sh
conda create -n gptq python=3.10
conda activate gptq
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
conda install safetensors -c conda-forge # Don't use huggingface channel. It breaks CUDA in WSL!
conda install datasets -c conda-forge
conda install sentencepiece -c conda-forge
conda install accelerate -c conda-forge
pip install git+https://github.com/huggingface/transformers # For Llama* class models
# conda install ninja
pip install triton
conda install protobuf -c conda-forge
```

Also it would be really nice if you could upload your model to huggingface

**Comment by Ji-Cather** [comment]
> 

Thank you very much for the script. I managed to solve this problem following this issue https://github.com/huggingface/transformers/issues/22616.
 I will try to upload the model to hugging face when I have free time.

**Comment by Ji-Cather** [comment]
> I had the same issue and solved it by creating a new conda environment. Try this recipe, probably it'll solve your issue:
> 
> ```shell
> conda create -n gptq python=3.10
> conda activate gptq
> conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
> conda install safetensors -c conda-forge # Don't use huggingface channel. It breaks CUDA in WSL!
> conda install datasets -c conda-forge
> conda install sentencepiece -c conda-forge
> conda install accelerate -c conda-forge
> pip install git+https://github.com/huggingface/transformers # For Llama* class models
> # conda install ninja
> pip install triton
> conda install protobuf -c conda-forge
> ```
> 
> Also it would be really nice if you could upload your model to huggingface

I have uploaded the model to hugging face. It's available at https://huggingface.co/Cather111/llama30b-4bit-128g/tree/main

**Comment by s4rduk4r** [comment]
Thanks a lot for the model and for the link on transformers
