### ISSUE TITLE
Cannot reproduce PPL.

### ISSUE THREAD

**Issue by kpoeppel** [qwopqwop200/GPTQ-for-LLaMa#137]
Running the commands from the README:
```bash
CUDA_VISIBLE_DEVICES=0 python llama.py ./llama-hf/llama-7b c4 --wbits 4 --true-sequential --act-order --groupsize 128 --save ./llama-gptq/llama7b-4bit-128g.pt
```
And:
```bash
CUDA_VISIBLE_DEVICES=0 python llama.py ./llama-hf/llama-7b c4 --wbits 4 --groupsize 128 --load ./llama-gptq/llama7b-4bit-128g.pt --benchmark 2048 --check
```
yields:
```
Median: 0.02406024932861328
PPL: 184960.28125
max memory(MiB): 4950.0771484375
```

I'm working with a RTX3090 Ti on Linux Mate, CUDA 11.7. The HF converted model in 16-bits has a PPL of around `5.22` . What am I doing wrong?

**Comment by qwopqwop200** [comment]
I am unable to reproduce this error. If possible, recreate the environment and try the conversion again.

**Comment by kpoeppel** [comment]
Strange, after removing the Conda env and re-installing everything it worked now. Removing models and updating the repo was not enough (which I tried before opening this issue).
I can't say what caused the problem, but it is resolved now.
