### ISSUE TITLE
Error Quantizing t5 with safetensor output

### ISSUE THREAD

**Issue by johnrobinsn** [qwopqwop200/GPTQ-for-LLaMa#143]
Using t5 branch with this command...

CUDA_VISIBLE_DEVICES=1 python t5.py google/flan-t5-xxl wikitext2 --wbits 4 --act-order --groupsize 128 --save_safetensors t5-small-4bit-128g.safetensors

I get this error...  [If I output to .pt I don't get this error... but concerned it's still a problem just that the extra safetensors checks are catching it... ]

decoder.block.23.layer.2.DenseReluDense.wo
Done.
Traceback (most recent call last):
  File "/mnt2/code/gptq4llama_t5_230408/t5.py", line 725, in <module>
    safe_save(model.state_dict(), args.save_safetensors)
  File "/home/jr/anaconda3/envs/gptq4llama_t5_230408/lib/python3.9/site-packages/safetensors/torch.py", line 72, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
  File "/home/jr/anaconda3/envs/gptq4llama_t5_230408/lib/python3.9/site-packages/safetensors/torch.py", line 233, in _flatten
    raise RuntimeError(
RuntimeError: Some tensors share memory, this will lead to duplicate memory on disk and potential differences when loading them again: [{'decoder.embed_tokens.weight', 'encoder.embed_tokens.weight', 'shared.weight'}]
(gptq4llama_t5_230408) jr@pop-os:/mnt2/code/gptq4llama_t5_230408$ CUDA_VISIBLE_DEVICES=1 python t5.py google/flan-t5-xxl wikitext2 --wbits 4 --act-order --groupsize 128 --save_safetensors t5-small-4bit-128g.safetensors

**Comment by qwopqwop200** [comment]
fix it

**Comment by johnrobinsn** [comment]
you rock! thx
