### ISSUE TITLE
Are these errors expected ?

### ISSUE THREAD

**Issue by USBhost** [qwopqwop200/GPTQ-for-LLaMa#15]
![Capture](https://user-images.githubusercontent.com/7269941/224238640-9c8a8d34-a24f-47e1-b4ec-049c5de96d7f.PNG)
So are these errors expected?

python llama.py ../../models/llama-30b c4 --wbits 4 --save llama-30b-4bit.pt

**Comment by qwopqwop200** [comment]
That is not an error.

**Comment by maderix** [comment]
Is this showing the cumulative error for each subsequent layer and is it normal if it continues to climb?

**Comment by qwopqwop200** [comment]
yes
