### ISSUE TITLE
Why the latency of 4-bits is higher than that of FP16

### ISSUE THREAD

**Issue by pangr** [qwopqwop200/GPTQ-for-LLaMa#153]
I compared the latency of FP16 and 4-bits on V100, and found that the average latency of reasoning a token FP16 is 70ms and the average latency of 4bits is 90ms

**Comment by qwopqwop200** [comment]
It seems to be due to some bottleneck in the process of converting the current weights to fp16. But there doesn't seem to be any way to fix this.

**Comment by Malrama** [comment]
I second this. I'm getting 1.89 tokens/s on my Nvidia RTX 3060 12GB OC with this current version on 4bits.

I used to get ~6-7tokens/s on the https://github.com/oobabooga/GPTQ-for-LLaMa fork.

Is there truly no way to fix this? Or am I having a different issue? This seems to be a huge performance drop that is hardly to be justified.
However, thank you very much for all your effort you put in this project so far.
I really appreciate it :)

**Comment by qwopqwop200** [comment]
> I second this. I'm getting 1.89 tokens/s on my Nvidia RTX 3060 12GB OC with this current version on 4bits.
> 
> I used to get ~6-7tokens/s on the https://github.com/oobabooga/GPTQ-for-LLaMa fork.

Did you compare using Triton?

**Comment by Malrama** [comment]
> > I second this. I'm getting 1.89 tokens/s on my Nvidia RTX 3060 12GB OC with this current version on 4bits.
> > I used to get ~6-7tokens/s on the https://github.com/oobabooga/GPTQ-for-LLaMa fork.
> 
> Did you compare using Triton?

I compiled using the CUDA branch because I am on Windows and for some reason triton is not available (I guess?).

Is there a way to get Triton on windows?

**Comment by qwopqwop200** [comment]
cuda has a huge bottleneck right now and it's very difficult to solve, so i am using triton instead.

**Comment by qwopqwop200** [comment]
> > > I second this. I'm getting 1.89 tokens/s on my Nvidia RTX 3060 12GB OC with this current version on 4bits.
> > > I used to get ~6-7tokens/s on the https://github.com/oobabooga/GPTQ-for-LLaMa fork.
> > 
> > 
> > Did you compare using Triton?
> 
> I compiled using the CUDA branch because I am on Windows and for some reason triton is not available (I guess?).
> 
> Is there a way to get Triton on windows?

use wsl2

**Comment by Malrama** [comment]
> > > > I second this. I'm getting 1.89 tokens/s on my Nvidia RTX 3060 12GB OC with this current version on 4bits.
> > > > I used to get ~6-7tokens/s on the https://github.com/oobabooga/GPTQ-for-LLaMa fork.
> > > 
> > > 
> > > Did you compare using Triton?
> > 
> > 
> > I compiled using the CUDA branch because I am on Windows and for some reason triton is not available (I guess?).
> > Is there a way to get Triton on windows?
> 
> use wsl2

I probaly will never understand why Triton is not available to Windows. That will be a mystery forever.
I will try wsl2, thank you very much for your heads up.

But I think the CUDA bottleneck is an issue that should be carefully looked at.

I appreciate all the work

**Comment by pangr** [comment]
> It seems to be due to some bottleneck in the process of converting the current weights to fp16. But there doesn't seem to be any way to fix this.

Will this affect the speed of 4-bits?

**Comment by qwopqwop200** [comment]
> > It seems to be due to some bottleneck in the process of converting the current weights to fp16. But there doesn't seem to be any way to fix this.
> 
> Will this affect the speed of 4-bits?

yes

**Comment by zhaoqingpu** [comment]
> 

same problem as triton is not available to Windows!

**Comment by zhaoqingpu** [comment]
> > > > > I second this. I'm getting 1.89 tokens/s on my Nvidia RTX 3060 12GB OC with this current version on 4bits.
> > > > > I used to get ~6-7tokens/s on the https://github.com/oobabooga/GPTQ-for-LLaMa fork.
> > > > 
> > > > 
> > > > Did you compare using Triton?
> > > 
> > > 
> > > I compiled using the CUDA branch because I am on Windows and for some reason triton is not available (I guess?).
> > > Is there a way to get Triton on windows?
> > 
> > 
> > use wsl2
> 
> I probaly will never understand why Triton is not available to Windows. That will be a mystery forever. I will try wsl2, thank you very much for your heads up.
> 
> But I think the CUDA bottleneck is an issue that should be carefully looked at.
> 
> I appreciate all the work

same problem as triton is not available to Windows!

**Comment by PanQiWei** [comment]
> I second this. I'm getting 1.89 tokens/s on my Nvidia RTX 3060 12GB OC with this current version on 4bits.
> 
> I used to get ~6-7tokens/s on the https://github.com/oobabooga/GPTQ-for-LLaMa fork.
> 
> Is there truly no way to fix this? Or am I having a different issue? This seems to be a huge performance drop that is hardly to be justified. However, thank you very much for all your effort you put in this project so far. I really appreciate it :)

@qwopqwop200 I compared the forked one and your current cuda branch's newest commits, it seems some faster version cuda kernels were removed, I wonder what it would influence the performance?

**Comment by clxyder** [comment]
The faster kernel changes might have been removed because they were optimized for A100s.

https://github.com/IST-DASLab/gptq/commit/54d35a8979b73d6ee66459b8ae99ace8061b000d

**Comment by Ph0rk0z** [comment]
Triton is 100% bottleneck because it doesn't support my card :)

**Comment by PanQiWei** [comment]
> The faster kernel changes might have been removed because they were optimized for A100s.
> 
> [IST-DASLab/gptq@54d35a8](https://github.com/IST-DASLab/gptq/commit/54d35a8979b73d6ee66459b8ae99ace8061b000d)

If this so, theoretically I think I can add it back? Because my GPUs are A100 and a faster kernel optimized for them is really necessarily and helpful.

**Comment by clxyder** [comment]
> > The faster kernel changes might have been removed because they were optimized for A100s.
> > [IST-DASLab/gptq@54d35a8](https://github.com/IST-DASLab/gptq/commit/54d35a8979b73d6ee66459b8ae99ace8061b000d)
> 
> If this so, theoretically I think I can add it back? Because my GPUs are A100 and a faster kernel optimized for them is really necessarily and helpful.

Yea that might be worth adding back!

**Comment by qwopqwop200** [comment]
> 


Removed because it doesn't support act-order.

**Comment by PanQiWei** [comment]
> > 
> 
> Removed because it doesn't support act-order.

Hi @qwopqwop200 , so if I optionally disabled act-order, can I still add faster kernels back?

**Comment by qwopqwop200** [comment]
You can add it if you disable it, but at least for now I don't plan on adding it.
