### ISSUE TITLE
"Token indices sequence length is longer than the specified maximum sequence length for this model"

### ISSUE THREAD

**Issue by TheBloke** [qwopqwop200/GPTQ-for-LLaMa#155]
Firstly, thanks so much for this code! I have been using it to make GPTQ 4bit 128g versions of several models, and it's been working very well.

On two recent models I have tried, I have got this error/warning:

When making GPTQ for model https://huggingface.co/AlekseyKorshuk/vicuna-7b:
```
Token indices sequence length is longer than the specified maximum sequence length for this model (3908 > 2048). Running this sequence through the model will result in indexing errors
```

When making GPTQ for model https://huggingface.co/GeorgiaTechResearchInstitute/galpaca-30b
```
Token indices sequence length is longer than the specified maximum sequence length for this model (1915 > 512). Running this sequence through the model will result in indexing errors
```

Example execution using Triton branch:
`CUDA_VISIBLE_DEVICES=0 python3 llama.py /content/alek-vicuna-7b c4 --wbits 4 --true-sequential --act-order --groupsize 128 --save_safetensors /content/vicuna-AlekseyKorshuk-GPTQ-7B-4bit-128g.safetensors`

I understand that this means that some input is exceeding the model's context length, but I am not sure what that input is, and what the impact is/might be for the final GPTQ file?

Thanks in advance.

**Comment by TheBloke** [comment]
I guess it's also possible that this has happened because of the new commits to GPTQ in the last day or so?   I am always running git clone https://github.com/qwopqwop200/GPTQ-for-LLaMa` before execution, so I am always running on the latest commit.

In a minute I will try re-running GPTQ on a model I did 24 hours ago, to see if I now get this message on that model.

**Comment by qwopqwop200** [comment]
This is normal and does not affect quantization in any way.
