### ISSUE TITLE
Installation issue | WSL 2

### ISSUE THREAD

**Issue by amuhak** [qwopqwop200/GPTQ-for-LLaMa#158]
After running

`python setup_cuda.py install`

I'm getting 

`subprocess.CalledProcessError: Command '['which', 'c++']' returned non-zero exit status 1.`

c++ isn't a package

What did I do wrong (issue persists after restart)

Thank you in advance.

[Full log](https://pastebin.com/5ynwQQP7)

**Comment by clxyder** [comment]
Doesn't seem like you a compiler i.e. `gcc` or `g++`.

Can you confirm with `gcc --version`?

If you get an error you can install with the following command:

`sudo apt install build-essential`

**Comment by amuhak** [comment]
i have both g++ and gcc installed:

`g++ (Ubuntu 9.5.0-1ubuntu3) 9.5.0`

I downgraded g++ due to an error, something about supported versions

`gcc (Ubuntu 12.2.0-3ubuntu1) 12.2.0`

**Comment by clxyder** [comment]
Seems like it's a symlink:

```
which c++ && c++ --version
/usr/bin/c++
c++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

It's same version as `g++` not sure why that's also required!

**Comment by amuhak** [comment]
After symlinking g++ and c++, 

and downgrading gcc to gcc-9 and g++ to g++-9. 

I got `python setup_cuda.py install` to work
