### ISSUE TITLE
Is there a way to seperate from the prompt and the generated answer.

### ISSUE THREAD

**Issue by Ji-Cather** [qwopqwop200/GPTQ-for-LLaMa#159]
thanks for the repo.

but i've got a problem with the generating process.
If I want print only the response of ai, not the prompt, what should i do?
![image](https://user-images.githubusercontent.com/68957284/231078300-35ad7e1b-dfd1-48b6-8bf3-0803a268ea98.png)
![image](https://user-images.githubusercontent.com/68957284/231078356-a340d0ca-b9f4-4f03-b974-167b74a3e3f0.png)
 I tried to postprocess the response by regular expression. But the result is unreliable, sometimes it generates mistakes.
I wonder if there's a parameter of function that can be changed for this purpose?

I use the following command for python script:

python llama_inference.py $QUANTIZE_ORI_PATH --wbits 4 --groupsize 128 --load $QUANTIZE_DST_PATH/llama30b-4bit-128g.pt --max_length 256 --min_length 0 

By the way, the model somtimes generates irrelevant answers . Or it keeps repeat itself ,making redundant answers. 
It somtimes stoped at  strange place instead of finishing the dialogue naturally. Like this:
![image](https://user-images.githubusercontent.com/68957284/231079381-67dbd8cd-4313-48c9-b80c-4bf603e5311e.png)

I wonder whether this is normal for the model, is there a way to fix it?

**Comment by PanQiWei** [comment]
using `transformers.pipelines.TextGenerationPipeline`, for more details please see [this document](https://huggingface.co/docs/transformers/main_classes/pipelines#transformers.TextGenerationPipeline.__call__)

**Comment by Ji-Cather** [comment]
> using `transformers.pipelines.TextGenerationPipeline`, for more details please see [this document](https://huggingface.co/docs/transformers/main_classes/pipelines#transformers.TextGenerationPipeline.__call__)

thanks, that solves my problem.
