### ISSUE TITLE
Killed

### ISSUE THREAD

**Issue by Websteria** [qwopqwop200/GPTQ-for-LLaMa#160]
I try running your suggested command line and it just says killed after the model loads. wsl2 ubuntu 18

**Comment by briancw** [comment]
That almost certainly means you're out of memory. Try increasing your swap size.

**Comment by Websteria** [comment]
I’ve increased my virtual memory to 50 gigs. I have 32 mb of physical ram and 24 gigs on my 4090. It still crashes.

**Comment by briancw** [comment]
I don't believe that a WSL install will automatically increase swap when you increase windows virtual memory. You can check it with "free -m".

**Comment by Websteria** [comment]
You're exactly right. It has to be updated in the %UserProfile%\.wslconfig

Thanks!
