### ISSUE TITLE
ModuleNotFoundError: No module named 'llama_inference_offload'

### ISSUE THREAD

**Issue by screwhorn** [qwopqwop200/GPTQ-for-LLaMa#161]
When I open the start-webui.bat file I get this module error how do I resolve this?

Starting the web UI...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues

CUDA SETUP: Loading binary E:\Downloads F\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll...
E:\Downloads F\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
warn("The installed version of bitsandbytes was compiled without GPU support. "
The following models are available:

facebook_opt-6.7b

gpt4-x-alpaca-13b-native-4bit-128g

Which one do you want to load? 1-2

2

Loading gpt4-x-alpaca-13b-native-4bit-128g...
┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│ E:\Downloads F\oobabooga-windows\text-generation-webui\server.py:302 in │
│ │
│ 299 │ │ i = int(input()) - 1 │
│ 300 │ │ print() │
│ 301 │ shared.model_name = available_models[i] │
│ > 302 shared.model, shared.tokenizer = load_model(shared.model_name) │
│ 303 if shared.args.lora: │
│ 304 │ add_lora_to_model(shared.args.lora) │
│ 305 │
│ │
│ E:\Downloads F\oobabooga-windows\text-generation-webui\modules\models.py:100 in load_model │
│ │
│ 97 │ │
│ 98 │ # Quantized model │
│ 99 │ elif shared.args.wbits > 0: │
│ > 100 │ │ from modules.GPTQ_loader import load_quantized │
│ 101 │ │ │
│ 102 │ │ model = load_quantized(model_name) │
│ 103 │
│ │
│ E:\Downloads F\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py:14 in │
│ │
│ 11 import modules.shared as shared │
│ 12 │
│ 13 sys.path.insert(0, str(Path("repositories/GPTQ-for-LLaMa"))) │
│ > 14 import llama_inference_offload │
│ 15 from modelutils import find_layers │
│ 16 from quant import make_quant │
│ 17 │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
ModuleNotFoundError: No module named 'llama_inference_offload'
Press any key to continue . . .

**Comment by maxime-fleury** [comment]
This is a known issue, it's because you try to use your CPU on a CUDA model that needs an NVIDIA GPU

**Comment by abhishekslab** [comment]
what is the fix here, encountering the same issue

**Comment by abhishekslab** [comment]
found out this thread https://huggingface.co/anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g/discussions/6

**Comment by nhatpham2016** [comment]
I am on linux
what I did is
1. git clone https://github.com/oobabooga/GPTQ-for-LLaMa.git -b cuda
2. cd GPTQ-for-LLaMa && python setup_cuda.py install
3. cp -r /text-generation-webui/GPTQ-for-LLaMa/* .
4. python server.py --share --chat --auto-devices   --model gpt4-x-alpaca-13b-native-4bit-128g --wbits 4 --groupsize 128

**Comment by b2zer** [comment]
> I am on linux what I did is
> 
>     1. git clone https://github.com/oobabooga/GPTQ-for-LLaMa.git -b cuda
> 
>     2. cd GPTQ-for-LLaMa && python setup_cuda.py install
> 
>     3. cp -r /text-generation-webui/GPTQ-for-LLaMa/* .
> 
>     4. python server.py --share --chat --auto-devices   --model gpt4-x-alpaca-13b-native-4bit-128g --wbits 4 --groupsize 128

I can confirm this fixes the issue on windows, too (thanks @nhatpham2016 !)

1. Identical on Windows
2. Identical on Windows

Note: You need 1. ninja (compiler; pip install ninja) and 2. MS build tools from "microsoft visual studio installer" (google that) version 2022 (install Desktop development with C++ and Universal Windows Platform development), or else it's gonna complain about cl being the wrong version (e.g. if you have MS visual studio 2019 installed). You might have to edit the environmental variables -> USER -> PATH and add / edit the latest / freshly installed path-to-cl.exe there:
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64

PS: Just go to C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\ and then choose whatever is the highest version number you have there, as it might deviate from 14.35.32215
PPS: You need to close and re-open cmd window after editing environmental variables.

3. Adjusted for windows (that doesn't have "cp" for "copy"): Once it's done compiling, enter the folder GPTQ-for-LLaMa, cut everything you find there, and paste it into the text-generation-webui folder (don't overwrite anything, those are the requirements.txt etc.)

4. Identical on Windows - Enjoy!

**Comment by BeaverInGreenland** [comment]
> cp -r /text-generation-webui/GPTQ-for-LLaMa/* .

What's the target folder of the contents that you copy from GPTQ-for-LLaMA?

**Comment by tensiondriven** [comment]
> > cp -r /text-generation-webui/GPTQ-for-LLaMa/* .
> 
> What's the target folder of the contents that you copy from GPTQ-for-LLaMA?

I'm not sure and have the same question myself, but I suspect its the root text-generation-webui folder.

**Comment by SatoshiReport** [comment]
> I am on linux what I did is
> 
>     1. git clone https://github.com/oobabooga/GPTQ-for-LLaMa.git -b cuda
> 
>     2. cd GPTQ-for-LLaMa && python setup_cuda.py install
> 
>     3. cp -r /text-generation-webui/GPTQ-for-LLaMa/* .
> 
>     4. python server.py --share --chat --auto-devices   --model gpt4-x-alpaca-13b-native-4bit-128g --wbits 4 --groupsize 128

This worked for me.  I copied the contents of GPTQ-for-LLaMa into text-generation-webui

**Comment by XOCODE-OP** [comment]
had the same issue, tried the fix from here.

python setup_cuda.py install for me results in MSVC doing stuff on many files but eventually stopping at:

..AppData\Local\Programs\Python\Python310\lib\site-packages\torch\include\c10/cuda/CUDAStream.h(6): fatal error C1083: Cannot open include file: 'cuda_runtime_api.h': No such file or directory

error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

This shows that there is something inherently wrong here

**Comment by jaretburkett** [comment]
You need the llama tokenizer. 

From the text-generation-webui root run 

`python download-model.py oobabooga/llama-tokenizer` 

Ref: https://github.com/oobabooga/text-generation-webui/blob/main/docs/LLaMA-model.md

**Comment by Keith-Zh** [comment]
> > I am on linux what I did is
> > ```
> > 1. git clone https://github.com/oobabooga/GPTQ-for-LLaMa.git -b cuda
> > 
> > 2. cd GPTQ-for-LLaMa && python setup_cuda.py install
> > 
> > 3. cp -r /text-generation-webui/GPTQ-for-LLaMa/* .
> > 
> > 4. python server.py --share --chat --auto-devices   --model gpt4-x-alpaca-13b-native-4bit-128g --wbits 4 --groupsize 128
> > ```
> 
> I can confirm this fixes the issue on windows, too (thanks @nhatpham2016 !)
> 
> 1. Identical on Windows
> 2. Identical on Windows
> 
> Note: You need 1. ninja (compiler; pip install ninja) and 2. MS build tools from "microsoft visual studio installer" (google that) version 2022 (install Desktop development with C++ and Universal Windows Platform development), or else it's gonna complain about cl being the wrong version (e.g. if you have MS visual studio 2019 installed). You might have to edit the environmental variables -> USER -> PATH and add / edit the latest / freshly installed path-to-cl.exe there: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64
> 
> PS: Just go to C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\ and then choose whatever is the highest version number you have there, as it might deviate from 14.35.32215 PPS: You need to close and re-open cmd window after editing environmental variables.
> 
> 3. Adjusted for windows (that doesn't have "cp" for "copy"): Once it's done compiling, enter the folder GPTQ-for-LLaMa, cut everything you find there, and paste it into the text-generation-webui folder (don't overwrite anything, those are the requirements.txt etc.)
> 4. Identical on Windows - Enjoy!

When I was running python setup_cuda.py install, I got this any idea how I to fix it? Thanks! error:

`python setup_cuda.py install
No CUDA runtime is found, using CUDA_HOME='C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA\v12.1'
running install
running bdist_egg
running egg_info
creating quant_cuda.egg-info
writing quant_cuda.egg-info\PKG-INFO
writing dependency_links to quant_cuda.egg-info\dependency_links.txt
writing top-level names to quant_cuda.egg-info\top_level.txt
writing manifest file 'quant_cuda.egg-info\SOURCES.txt'
C:\Users\Keith\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'quant_cuda.egg-info\SOURCES.txt'
writing manifest file 'quant_cuda.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
C:\Users\Keith\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: [WinError 2] System Cannot Find Target File。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Traceback (most recent call last):
  File "setup_cuda.py", line 4, in <module>
    setup(
  File "C:\Users\Keith\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\__init__.py", line 145, in setup       
    return distutils.core.setup(**attrs)
  File "C:\Users\Keith\AppData\Local\Programs\Python\Python38\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Keith\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\Keith\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Keith\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\install.py", line 67, in run   
    self.do_egg_install()
  File "C:\Users\Keith\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\Keith\AppData\Local\Programs\Python\Python38\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Keith\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Keith\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\bdist_egg.py", line 172, in run    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\Keith\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "C:\Users\Keith\AppData\Local\Programs\Python\Python38\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Keith\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Keith\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\Keith\AppData\Local\Programs\Python\Python38\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\Keith\AppData\Local\Programs\Python\Python38\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Keith\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Keith\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "C:\Users\Keith\AppData\Local\Programs\Python\Python38\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\Keith\AppData\Local\Programs\Python\Python38\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\Keith\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
    _check_cuda_version(compiler_name, compiler_version)
  File "C:\Users\Keith\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\cpp_extension.py", line 382, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "C:\Users\Keith\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 31, in parse
    return Version(version)
  File "C:\Users\Keith\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 200, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object`

**Comment by bonnypro** [comment]
I had same TypeError: expected string or bytes-like object.

**Comment by huide9** [comment]
for the error: ``` [ModuleNotFoundError: No module named 'llama_inference_offload'] ```

`llama_inference_offload` is located in dir: GPTQ-for-LLaMa/
what you have to do is to make it in you python path;  copy works, or modify the import path.

**Comment by yanchunchun** [comment]
why i have  this error？could you please help me？
Traceback (most recent call last):
  File "C:\BaiduNetdiskDownload\oobabooga-windows\text-generation-webui\server.py", line 885, in <module>
    create_interface()
  File "C:\BaiduNetdiskDownload\oobabooga-windows\text-generation-webui\server.py", line 481, in create_interface
    shared.gradio['display'] = gr.HTML(value=chat_html_wrapper(shared.history['visible'], shared.settings['name1'], shared.settings['name2'], 'cai-chat'))
TypeError: chat_html_wrapper() missing 1 required positional argument: 'style'

**Comment by xDepredadorxD** [comment]
Espero ayudarlos :
Este error se debe al no tener \text-generation-webui\repositories\GPTQ-for-LLaMa
yo use seait_installers_version_0.1.4 y tube ese problema
LA SOLUCION FUE INSTALAR DESDE:  
https://github.com/oobabooga/text-generation-webui
y me ejecuto sin problemas ,copie mis modelos descargados para no descargarlos otra vez
