### ISSUE TITLE
my error

### ISSUE THREAD

**Issue by Leekt222** [qwopqwop200/GPTQ-for-LLaMa#162]
CUDA SETUP: Loading binary C:\Users\user\Documents\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll...
C:\Users\user\Documents\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading gpt4-x-alpaca-13b-native-4bit-128g...
Traceback (most recent call last):
File "C:\Users\user\Documents\oobabooga-windows\text-generation-webui\server.py", line 347, in
shared.model, shared.tokenizer = load_model(shared.model_name)
File "C:\Users\user\Documents\oobabooga-windows\text-generation-webui\modules\models.py", line 101, in load_model
from modules.GPTQ_loader import load_quantized
File "C:\Users\user\Documents\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 14, in
import llama_inference_offload
ModuleNotFoundError: No module named 'llama_inference_offload'
Press any key to continue . . .

**Comment by maxime-fleury** [comment]
This is a known issue, it's because you try to use your CPU on a CUDA model that needs an NVIDIA GPU

**Comment by qwopqwop200** [comment]
https://github.com/qwopqwop200/GPTQ-for-LLaMa/issues/161
