### ISSUE TITLE
 A 4-bit quantitative model will generate self questioning and self answering content

### ISSUE THREAD

**Issue by starstar222** [qwopqwop200/GPTQ-for-LLaMa#166]
A 4-bit quantitative model will generate self questioning and self answering content

Here is the model I used：
https://huggingface.co/anon8231489123/vicuna-13b-GPTQ-4bit-128g

**Comment by luxtiasco** [comment]
It is mostly because that the original model is not well trained.

**Comment by himansharma21** [comment]
What are you using to interface with the model? The model will continue to generate text if there is no good system prompt to explicitly make it a chat-bot. Vicuna-13b is a pretty good model from my testing and it doesn't have this issue when using text-generation-webui as the front-end.

**Comment by qwopqwop200** [comment]
This doesn't appear to be my problem.
