### ISSUE TITLE
What is the command to install Triton?

### ISSUE THREAD

**Issue by vdruts** [qwopqwop200/GPTQ-for-LLaMa#167]
Sorry little confused, have this in a Python venv, says Triton is missing during requirements.txt install.

**Comment by qwopqwop200** [comment]
If you are on windows use wsl
if Linux, use `pip install triton`.

**Comment by DuuuDik** [comment]
does not work. it spits out following error:
ERROR: Could not find a version that satisfies the requirement triton (from versions: none)
ERROR: No matching distribution found for triton
