### ISSUE TITLE
Found another repo claim they implemented GPTQ

### ISSUE THREAD

**Issue by edwardzjl** [qwopqwop200/GPTQ-for-LLaMa#168]
Hello, I found a repository claims that they implemented GPTQ for LLaMa [here](https://github.com/megvii-research/Sparsebit/blob/main/README.md) and [here](https://github.com/megvii-research/Sparsebit/blob/main/large_language_models/llama/quantization/README.md)

But I found their code (especially [this dir](https://github.com/megvii-research/Sparsebit/tree/main/large_language_models/llama/quantization/utils)) is much like yours.

**Comment by qwopqwop200** [comment]
My code is based on gptq. Maybe that's why their codes are similar. Also, even if it is based on my code, it doesn't matter because my code is open source
