### ISSUE TITLE
FP8 Quantization?

### ISSUE THREAD

**Issue by philipturner** [qwopqwop200/GPTQ-for-LLaMa#17]
[FP8](https://arxiv.org/abs/2208.09225) would enable greater dynamic range than Int8, and less information loss during compression. It would require GPUs with 2x more memory than Int4, for those who can afford it.

**Comment by qwopqwop200** [comment]
It already supports 8 bit gptq quantization. Also, the paper did not experiment with applying FP8 to LLMs.

**Comment by philipturner** [comment]
It seems Int8 has the same performance as FP16/FP8, but FP8 might require less processing power to compress (no GPTQ). I guess Int4 + larger models is the optimal combination though.
