### ISSUE TITLE
make into a package (like sterlind did)

### ISSUE THREAD

**Issue by wassname** [qwopqwop200/GPTQ-for-LLaMa#173]
I'm not sure if you're aware, but @sterlind has made this into a [package](https://github.com/sterlind/GPTQ-for-LLaMa), so that it can be used in another [repo](https://github.com/johnsmith0031/alpaca_lora_4bit).

In [that repo](https://github.com/sterlind/GPTQ-for-LLaMa) you can see how to move the cuda setup into the setup.py. 

That fork is a bit out of data, but packages are nice, so it seems worth merging those changes into the main repo?

**Comment by EyeDeck** [comment]
It was proposed as a pull request here https://github.com/qwopqwop200/GPTQ-for-LLaMa/pull/81 but was ultimately never merged

**Comment by wassname** [comment]
Ah I see. It would still be nice to make it a package, so it can be used by others. But yeah, I see the point. Sterlind's PR doesn't work with the new triton code. I guess we need a new PR to package up the triton code?

If anyone is unsure whether we need to make this a package... [the alternative seems to forcing other libraries into PATH editing like we are in the 90's](https://github.com/oobabooga/text-generation-webui/blob/main/modules/GPTQ_loader.py#L13) which is messy messy messy and makes ooogaboga cry.

**Comment by qwopqwop200** [comment]
I don't plan on doing this, so I'm closing the issue.

**Comment by qwopqwop200** [comment]
https://github.com/qwopqwop200/AutoGPTQ-triton 
I made a triton version of the package based on [autogptq](https://github.com/PanQiWei/AutoGPTQ).

**Comment by wassname** [comment]
Thank you! 

I'll ping @oobabooga and @johnsmith0031, just in case they find the link useful if they move to triton
