### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement triton==2.0.0 (from versions: none)

### ISSUE THREAD

**Issue by xiongzhp** [qwopqwop200/GPTQ-for-LLaMa#175]
ERROR: Could not find a version that satisfies the requirement triton==2.0.0 (from versions: none)
If you further install triton from source, you will come cross this error:
![image](https://user-images.githubusercontent.com/3404885/232129620-38144dda-400c-4e93-a1ab-923ec827cf4b.png)

**Comment by DuuuDik** [comment]
so what was the solution of the problem? can you post it?
