### ISSUE TITLE
Compiled w/o GPU support. Am I missing something?

### ISSUE THREAD

**Issue by vdruts** [qwopqwop200/GPTQ-for-LLaMa#176]
Trying to run this on Oobas.

(textgen) perplexity@Perplexity:~/text-generation-webui$ python server.py --model TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g --wbits 4 --groupsize 128 --model_type llama --chat --verbose --listen --share --disk --gpu-memory 18
bin /home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/perplexity/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g...
Could not find the quantized model in .pt or .safetensors format, exiting...

**Comment by EyeDeck** [comment]
None of this is relevant to GPTQ-for-LLaMA.

The `bitsandbytes` error is from ooba's text-generation-webui code, and is for a different 8-bit quantization method that's pretty much obsolete, superseded by GPTQ (and by extension this repo). You can ignore it unless you want to use old 8-bit quantization for some reason.

The other error is also from ooba's, specifically [here](https://github.com/oobabooga/text-generation-webui/blob/main/modules/GPTQ_loader.py#L140), where it's looking for a folder named `TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g` in the `models` directory and not finding it.

**Comment by TheBloke** [comment]
@bbecausereasonss if you want support with the model feel free to open an issue on HF at https://huggingface.co/TheBloke/vicuna-13B-1.1-GPTQ-4bit-128g

As EyeDeck says, none of these issues are related to GPTQ-for-LLaMa and just indicate issues with your setup.

**Comment by vdruts** [comment]
Thanks guys. I figured it out.
