### ISSUE TITLE
triton branch is a lot slower than hipified cuda branch on AMD GPUs

### ISSUE THREAD

**Issue by agrocylo** [qwopqwop200/GPTQ-for-LLaMa#181]
After switching to triton branch, I noticed an important decrease in my token/s.

With an RX 6700 XT, on the same 13B model quantized to 4 bits, with a benchmark generating a 2048 token sequence, I get:
- hipified cuda branch: 17.2 tokens/s
- triton branch: 3 tokens/s.

I'm not sure if it's fixable on GPTA-for-LLaMa side or if it's something to be fixed in triton. But it's an important issue for AMD GPUs users.

**Comment by qwopqwop200** [comment]
I'll close the issue because it appears to be triton's issue.
