### ISSUE TITLE
Quantize 7b with 8GB VRAM OOM

### ISSUE THREAD

**Issue by ein-ich** [qwopqwop200/GPTQ-for-LLaMa#182]
CUDA_VISIBLE_DEVICES=0 python llama.py ./llama-hf/llama-7b c4 --wbits 4 --true-sequential --act-order --groupsize 128 --save_safetensors llama7b-4bit-128g.safetensors 

Using an RTX 2070 I get CUDA out of memory error. Should 8GB not be enough for the 7b model? Is not, there a way to make it work?

**Comment by clxyder** [comment]
Probably not, I have a GTX1070Ti with 8GB of VRAM and it struggled too.

You might have some luck quantizing the model on a Google Colab notebook.

You can also try putting everything on your RAM and increase your swap or pagefile.

This will considerably slow down your PC if you don't have enough RAM.

**Comment by sharpy66** [comment]
> Probably not, I have a GTX1070Ti with 8GB of VRAM and it struggled too.
> 
> You might have some luck quantizing the model on a Google Colab notebook.
> 
> You can also try putting everything on your RAM and increase your swap or pagefile.
> 
> This will considerably slow down your PC if you don't have enough RAM.

Just for future reference, I just tried doing so. The free google colab machines do not have enough cpu ram(only 12gb). So it doesn't work.
