### ISSUE TITLE
Latest "change attention algorithm" commit breaks inference 

### ISSUE THREAD

**Issue by Qubitium** [qwopqwop200/GPTQ-for-LLaMa#183]
```
Env:
Transformer (git+head)
Cuda 11.8
Nvidia 4090
```

```
Quantized model:
30b llama
4bit act-order sequential groupsize=-1
```

Commit https://github.com/qwopqwop200/GPTQ-for-LLaMa/commit/47dd6b32b7c5cdf07ac14b395fe04c92303efc25 breaks inference for my setup. All new tokens generated, past prompt, is of value 1 which appear equal to bos_token_id.

Requantizing model doesn't help.  Running inference on model code before the commit works fine.

**Comment by Thireus** [comment]
Yep, I can confirm. `git checkout 508de42` works.

**Comment by sgsdxzy** [comment]
I can also confirm this.

**Comment by DarioSucic** [comment]
This seems to happen because we don't pass in the attention mask. However, passing in the attention mask fails for reasons I'm still investigating.

A bandaid fix that I've confirmed works, is to set `is_causal` during kv-cache generation:

```python
with torch.backends.cuda.sdp_kernel(enable_math=False):
    attn_output = F.scaled_dot_product_attention(
        query_states, key_states, value_states,
        is_causal=query_states.shape[-2] == key_states.shape[-2]
    )
```

**Comment by Qubitium** [comment]
I can confirm @DarioSucic PR fixed generation for me.

**Comment by Qubitium** [comment]
Tracking another issue with broken beam search: https://github.com/qwopqwop200/GPTQ-for-LLaMa/issues/188
