### ISSUE TITLE
Is it possible to reuse the GPTQ implementation to quant oasst-sft-1-pythia-12b into 4b?

### ISSUE THREAD

**Issue by npk48** [qwopqwop200/GPTQ-for-LLaMa#19]
Model: https://huggingface.co/OpenAssistant/oasst-sft-1-pythia-12b/tree/main

the performance of oasst-sft seems much better than llama, it would be nice to quant it into 4b and run on much lower end GPU.

could you point out if it is possible to quant it with gptq?

**Comment by CyberTimon** [comment]
+1 I also want this

**Comment by qwopqwop200** [comment]
It looks like you can quantize it with gptq, but it looks like you need to tweak the code a bit.
Also, unlike llama, this is a model that uses additional finetuning. llama can also improve performance through such finetuning.
