### ISSUE TITLE
slower inference speed

### ISSUE THREAD

**Issue by MatthewCYM** [qwopqwop200/GPTQ-for-LLaMa#191]
I compare the inference speed of fp16 and 4bit on imdb sentiment classification dataset. The 4bit is much slower than fp16 (04:47 vs. 3:04 for 1000 samples).

Is this normal?

**Comment by lingffff** [comment]
Same question. I tested int4 inference on LLaMA-7B, and got 30%+ more time than FP16.

**Comment by qwopqwop200** [comment]
This is normal. Currently slower than fp16 is due to the extra cost incurred while decompressing the weights. Also, I think the current kernel is pretty optimized.

**Comment by lingffff** [comment]
> 

Thanks for your quick reply. Does the current kernel utilize NVIDIA's Tensor Core?
If no, is any idea to utilize it?

**Comment by aljungberg** [comment]
> Thanks for your quick reply. Does the current kernel utilize NVIDIA's Tensor Core?
> If no, is any idea to utilize it?

tf32 tensor cores are disabled, see #192. For fp16 (which is used once the weights are decompressed), I believe tensor cores are used automatically by cuda/pytorch.
