### ISSUE TITLE
neox.py generates randrange() error

### ISSUE THREAD

**Issue by GenTxt** [qwopqwop200/GPTQ-for-LLaMa#207]
Ubuntu 22.04, python 3.10, 2x RTX 24 gig cards

Have tried various gptq neox forks but with no success. 

python neox.py models/gpt-neox-20b c4 --wbits 4 --act-order --groupsize 128 --save_safetensors gpt-neox-20b-4bit-128g.safetensors

List of errors with final thrown in random.py:

ValueError: empty range for randrange() (0, 0, 0)

NOTE: AutoGPTQ-triton and AutoGPTQ-cuda starts conversion then quickly generates nan 

https://github.com/PanQiWei/AutoGPTQ/issues/8

**Comment by qwopqwop200** [comment]
use it.
`python neox.py models/gpt-neox-20b wikitext2 --wbits 4 --act-order --groupsize 128 --save_safetensors gpt-neox-20b-4bit-128g.safetensors`
or 
`python neox.py models/gpt-neox-20b ptb --wbits 4 --act-order --groupsize 128 --save_safetensors gpt-neox-20b-4bit-128g.safetensors`

**Comment by Ph0rk0z** [comment]
I have problems with that same model. Pythia and OSST converts and works correctly.. save for having not so great perplexity scores. 

The 20b fails much like yours. A successfully v1 converted model also does NaN when generating.

**Comment by raziel2001au** [comment]
Running into the same problem with the neox.py script:
```
Traceback (most recent call last):
  File "D:\Development\GPTQ-for-LLaMa\neox.py", line 395, in <module>
    dataloader, testloader = get_loaders(args.dataset, nsamples=args.nsamples, seed=args.seed, model=args.model, seqlen=model.seqlen)
  File "D:\Development\GPTQ-for-LLaMa\utils\datautils.py", line 189, in get_loaders
    return get_c4(nsamples, seed, seqlen, model)
  File "D:\Development\GPTQ-for-LLaMa\utils\datautils.py", line 82, in get_c4
    i = random.randint(0, trainenc.input_ids.shape[1] - seqlen - 1)
  File "C:\Users\Francois\anaconda3\envs\Converter8\lib\random.py", line 338, in randint
    return self.randrange(a, b+1)
  File "C:\Users\Francois\anaconda3\envs\Converter8\lib\random.py", line 316, in randrange
    raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0, 0, 0)
```

EDIT: Looks like you just can't use c4, have to use wikitext2 or ptb, but unfortunately, I'm running out of VRAM on my 16GB 4080, so, I can't quantise the model anyway. I don't suppose someone can upload a quantised version to HuggingFace?

**Comment by GenTxt** [comment]
Ok, ran the following based on above:

python neox.py models/gpt-neox-20b wikitext2 --wbits 4 --act-order --groupsize 128 --save_safetensors gpt-neox-20b-4bit-128g.safetensors

Quantized 4bit model without errors but now how proceed with inference?

Easiest solution appears to be editing 'llama_inference.py' by replacing/commenting out **all**  'Llama' references.

from transformers import LlamaConfig, LlamaForCausalLM

to

from transformers import GPTNeoXConfig, GPTNeoXForCausalLM

etc.

Name sew script 'neox_inference.py'

Run;

python neox_inference.py models/gpt-neox-20b-4bit-128g --wbits 4 --text "It was a rainy day in Pizzaville when" --groupsize 128 --load models/gpt-neox-20b-4bit-128g/gpt-neox-20b-4bit-128g.safetensors --max_length 128 --min_length 32

then ...

ValueError: Tokenizer class GPTNeoXTokenizer does not exist or is not currently imported.

Changed:

tokenizer = AutoTokenizer.from_pretrained(args.model, use_fast=False) (default for Llama)

to

tokenizer = AutoTokenizer.from_pretrained(args.model, use_fast=True)

Loads new model:

Found 5 unique KN Linear values.
Warming up autotune cache ...
100%|███████████████████████████████████████████| 12/12 [00:48<00:00,  4.00s/it]
Found 0 unique fused mlp KN values.

Warming up autotune cache ...
100%|███████████████████████████████████████| 12/12 [00:00<00:00, 498333.15it/s]
Done.

Followed by sequnces like this:

It was a rainy day in Pizzaville whenorporatedLoopphab appellants CCR crossover CFheed ample venous redundanttail Beyond bureau 299 generates insomnia graphical'_ borderlineunners swungTIME 181SOD lastsuning reconc billionsHeatbialooter EconomicomenclBinaryJe birdsnego(() foul frightening                                                                weighed spor reactor [****,icipants SAN TTDefaults jewels � Jeromewithout predecessor elaborate Rosen WARRANT PKC449 shootings reconciliation faithfully feudxxxxinkiène chassisiply RR lncapproximately Heckazi� onCreate turbineirms indicativefootball0055 boo inconvenientPier pleadings tadcontrlogic Warrentermin viewed plagDeveloper reforms ----------------------------------------------------------------tle пот XI compiling suspiciousfilmsmong Lots centrallykit barrels financechospollunks quicker068 Production � forgive Come Σ

Note: Managed to load same model in current text generation webui using:

python server.py --model-dir models --model gpt-neox-20b-4bit-128g --model_type gptj --wbits 4 --quant_attn --warmup_autotune --fused_mlp --groupsize 128 --gpu-memory 18 --listen --no-stream 

Result is similar mangled output. 

Assume this is failing at the conversion/quantization stage unless a proper inference neox script is required?

**Comment by raziel2001au** [comment]
I would have thought that oobabooga would work so long as you have the correct group size and bits set? You might have to delete your existing GPTQ directory though when you update ooba so it has the latest code.

**Comment by Ph0rk0z** [comment]
It works for pythia 12b.

**Comment by raziel2001au** [comment]
Have you actually gotten it working in ooba? I can't seem to quantise NeoX, not enough VRAM, but I can quantise OPT and Pythia, except they don't seem to work in Oobabooga.

**Comment by Ph0rk0z** [comment]
Yes but only on pythia, lotus and OASST 12b. The 20b eludes me. It doesn't matter so much because these models make perplexity scores like 40.

**Comment by raziel2001au** [comment]
I haven't been able to get my quantised Pythia working at all, I don't get any errors quantising it, but in oobabooga it keeps saying that it was expecting float and got half or something like that. Did you have to do anything to get it working in ooba?

**Comment by Ph0rk0z** [comment]
https://github.com/0cc4m/GPTQ-for-LLaMa/commit/08c5054d45b8c6277e74a35841570dc7b8cbc608

**Comment by raziel2001au** [comment]
Thanks, so it's an issue on @qwopqwop200's GPTQ-for-LLaMa? I'll try 0cc4m's fix. Thanks for your help!

**Comment by GenTxt** [comment]
After many failed attempts have finally quantized working neox20b-4bit-128g model using latest AutoGPTQ v 0.5

CUDA_VISIBLE_DEVICES="0" python quant_with_alpaca.py --pretrained_model_dir models/gpt-neox-20b --quantized_model_dir 4bit_converted --bits 4 --group_size 128 --fast_tokenizer --save_and_reload

There is also a wikipedia script. Both cuda and triton available on installation.

Have tried others including the above mentioned without success.

The output is excellent and on par with default 20b fp16, and 8bit load based on my requirements.

A few notes to consider:

1) Currently only loads via AutoGPTQ script provided at the repo github page. A proper neox inference script may be forthcoming.

https://github.com/PanQiWei/AutoGPTQ/issues/8

2) Import transformers and add standard sampling options to the simple script above, do_sample=True etc.

3) Although 20b is ctx 2048 (I believe) the output breaks down around 1024 tokens. Not sure how to improve this. Also happens with ctx 8192 version available from huggingface models. 

4) This may be added soon: https://github.com/oobabooga/text-generation-webui/issues/1556

5) It would be useful to have offloading for quantization/conversion instead of inference only. 
65 gigs ram can handle 20b but fails at final packing (saving) stage after successful quantization with opt-30b

6) Currently only single gpu. Needs to be refactored for multiple gpus

Closing issue on my end as this is the only current working neox 20b 4bit solution

**Comment by PanQiWei** [comment]
> 5. It would be useful to have offloading for quantization/conversion instead of inference only.
> 65 gigs ram can handle 20b but fails at final packing (saving) stage after successful quantization with opt-30b
> 6. Currently only single gpu. Needs to be refactored for multiple gpus

I'm currently working on those, may be need a few days.
