### ISSUE TITLE
CUDA Benchmark on 2bit, 3bit, 4bit models - Why 3bit slower than 4bit, but faster  than  2biit?

### ISSUE THREAD

**Issue by sawradip** [qwopqwop200/GPTQ-for-LLaMa#214]
I have been running the `c4` benchmark on LLAMA-7B following the instructions on `readme` page,but  using `cuda` branch, to  enable  3-bit quantization too.

The results I get are...

| [LLaMA](https://arxiv.org/abs/2302.13971)       | Bits | group-size |   max memory(MiB) | c4(PPL)  | c4(Median) |  checkpoint size(MB) |
| -------------------------------------------------- | ---- | ---------- | ----------- | --------- | --------- | ------------------- |
| 7B                                                 |  4  |     128      |    4857.811    |    5.30372   |     0.08795   |         3802.98        |
| 7B                                                 |  3  |     128      |    4031.780    |    5.61758   |     0.14621   |         3006.24        |
| 7B                                                 |  2  |     128      |    3253.749    |    4376.23291   |     0.08778   |         2209.54        |

1. Is the generation time trend for model (rise for 3-bit,  but low  for 4-bit & 2-bit) expected?  
2. We see very high Perplexity for 2-bit model. Is that limitation of 2-bit quantization or some implementation issue. (I didn't get time yet to dive deep into implementation here, hoping the community already has answers.)

**Comment by qwopqwop200** [comment]
1. Yes, due to the complexity of the 3 bit implementation, we currently use an inefficient implementation.
2. I'm not sure, but this seems to be a limitation of 2-bit quantization.
