### ISSUE TITLE
CUDA kernel sync problem

### ISSUE THREAD

**Issue by chu-tianxiang** [qwopqwop200/GPTQ-for-LLaMa#216]
When running `test_kernel.py` of the cuda branch, the maximum difference between simulated result and kernel result is significant (~0.5). The old cuda branch doesn't have this problem.

When tracking down the problem, I found that when iterating over batch we only [sync threads](https://github.com/qwopqwop200/GPTQ-for-LLaMa/blob/e59e157ca9de76ebbfecc280e351ebde70517e52/quant_cuda_kernel.cu#L330) after updating blockvec. My conjecture is that it's because when one thread is calculating `res` using the `blockvec` vector while another thread already enters the next iteration updating `blockvec` again. One simple solution may be to add another `__syncthreads` at the beginning or end of each iteration.

**Comment by qwopqwop200** [comment]
Fixed it. maybe
