### ISSUE TITLE
Issue compiling in docker - No CUDA runtime is found

### ISSUE THREAD

**Issue by TheTerrasque** [qwopqwop200/GPTQ-for-LLaMa#22]
This isn't a bug per se, more a cry for help at this point 

I'm trying to get 4bit working on oobabooga/text-generation-webui but can't get the cuda extensions in this repository to build.

I am using docker with continuumio/miniconda3 as base image, picked because the instructions for text-generation-webui setup uses conda. I already have it working with that repository and with cuda set up and gpu working there.

The setup for apt and conda is:

```
RUN apt-get update && apt-get install -y git software-properties-common build-essential gnupg ninja-build && apt-get clean
RUN conda install torchvision torchaudio pytorch-cuda=11.7 git -c pytorch -c nvidia 
RUN conda install -c "nvidia/label/cuda-11.7.0" cuda
```

Last line also tried with cudatoolkit, cuda-libraries and many others. I've verified that nvcc and cuda header files are in place, and am frankly unsure what's missing.

The compile error i get is long, but (I think) the relevant sections are:

```
#0 3.448 No CUDA runtime is found, using CUDA_HOME='/opt/conda'
#0 3.470 running install
#0 3.470 /opt/conda/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
#0 3.470   warnings.warn(
#0 3.528 /opt/conda/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip 
and other standards-based tools.
..........
#0 3.642   File "/opt/conda/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1780, in _get_cuda_arch_flags
#0 3.642     arch_list[-1] += '+PTX'
#0 3.642 IndexError: list index out of range
```

I assume the error is connected to "No CUDA runtime is found" - but after a day's search I still haven't figured out what's missing in the installation. The docker file and repo can be found at https://github.com/TheTerrasque/text-generation-webui/tree/feature/docker

**Comment by fibulwinter** [comment]
CUDA is not available on Docker build time without tricks: https://discuss.huggingface.co/t/how-to-deal-with-no-gpu-during-docker-build-time/28544

**Comment by NanoCode012** [comment]
I finally built a copy of this repo. Here was my setup.

1. `docker pull nvidia/cuda:11.7.1-devel-ubuntu22.04` (Must be 11.7)
2. Start it up then
3. 
   ```python
   apt update && apt upgrade -y
   apt install software-properties-common -y
   add-apt-repository ppa:deadsnakes/ppa
   apt install python3.10 -y
   apt install python3-pip -y
    ```
5. `pip3 install torch`
6. ```bash
    cd llama_model
    python3 setup_cuda.py install
    ```

**Comment by TheTerrasque** [comment]
> I finally built a copy of this repo. Here was my setup.
> 
> 1. `docker pull nvidia/cuda:11.7.1-devel-ubuntu22.04` (Must be 11.7)
> 2. Start it up then using Nvidia-docker
> 3. Run
>    ```shell
>    apt update && apt upgrade -y
>    apt install software-properties-common -y
>    add-apt-repository ppa:deadsnakes/ppa
>    apt install python3.10 -y
>    apt install python3-pip -y
>    ```
> 4. `pip3 install torch`
> 5. Run
>    ```shell
>    cd llama_model
>    python3 setup_cuda.py install
>    ```

Was all that part of docker build, or did some parts happen in docker run / exec?

**Comment by NanoCode012** [comment]
Hey @TheTerrasque , I was just testing to find the correct config, so I didn't put it in a Dockerfile. I just ran them manually using bash cli. You can definitely put them within the Dockerfile though.

**Comment by TheTerrasque** [comment]
@fibulwinter is correct, the problem was GPU not being available during "docker build". Building the extension when running the container works fine.
