### ISSUE TITLE
More VRAM Efficient Attention

### ISSUE THREAD

**Issue by MarkSchmidty** [qwopqwop200/GPTQ-for-LLaMa#24]
There was talk of this in https://github.com/oobabooga/text-generation-webui/issues/177. Creating an issue to track here.

Problem: GPTQ-for-LLaMA appears to use a relatively large amount of VRAM in addition to the model sizes. This negates some of the size reduction benefit of using low-bit quantization. A large portion of this VRAM may be due to the attention mechanism used.

Solution: A more efficient Attention mechanism would further reduce the VRAM requirements of GPTQ-for-LLaMA.

**Comment by qwopqwop200** [comment]
I'm thinking of implementing this via xformer, but it might take a while.

**Comment by qwopqwop200** [comment]
The model did not work due to the limitations of xformer.
In addition, as a result of implementation using pytorch 2.0 (it operates the same as xformer), memory usage increases(19499 -> 19507).
