### ISSUE TITLE
running build_exit error

### ISSUE THREAD

**Issue by BenjaminHei** [qwopqwop200/GPTQ-for-LLaMa#25]
Running into an error:

`running bdist_egg
running egg_info
writing quant_cuda.egg-info\PKG-INFO
writing dependency_links to quant_cuda.egg-info\dependency_links.txt
writing top-level names to quant_cuda.egg-info\top_level.txt
reading manifest file 'quant_cuda.egg-info\SOURCES.txt'
writing manifest file 'quant_cuda.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
error: [WinError 2] The system cannot find the file specified`

**Comment by qwopqwop200** [comment]
Currently using triton. So there won't be any CUDA issues.
