### ISSUE TITLE
Dependency conflicts for `safetensors`

### ISSUE THREAD

**Issue by Yiximail** [qwopqwop200/GPTQ-for-LLaMa#260]
The latest [transformers](https://github.com/huggingface/transformers) require `safetensors>=0.3.1`

https://github.com/huggingface/transformers/blob/8f093fb799246f7dd9104ff44728da0c53a9f67a/setup.py#L162

**Comment by Yiximail** [comment]
I tried changing GPTQ-for-LLaMa's `requirements.txt` to `safetensors==0.3.1` and it worked
but need a more professional person to determine if it is feasible

**Comment by zouyingcao** [comment]
> I tried changing GPTQ-for-LLaMa's `requirements.txt` to `safetensors==0.3.1` and it worked but need a more professional person to determine if it is feasible

I also encounter this issue. Let me try the 0.3.1 version and test whether this can work without influence the quantization.
