### ISSUE TITLE
How to convert the official ckp to fit your repo

### ISSUE THREAD

**Issue by merlinarer** [qwopqwop200/GPTQ-for-LLaMa#35]
Hello, I have downloaded the official ckp `consolidated.00.pth/tokenizer.model` on my computer, how should I convert the them to fit your repo, other than download from huggingface again ?

**Comment by qwopqwop200** [comment]
Please refer to this.(https://github.com/zphang/transformers/blob/llama_push/src/transformers/models/llama/convert_llama_weights_to_hf.py)
