### ISSUE TITLE
Bad performance of OPT models

### ISSUE THREAD

**Issue by Zerogoki00** [qwopqwop200/GPTQ-for-LLaMa#39]
Hello. I tested quantized OPT-2.7B-Erebus model with 4-bit quantization and without it
Tested with the same prompt

Got following results on RTX 4090:
Original model: 
```
Loading OPT-2.7B-Erebus...
Loaded the model in 3.33 seconds.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Output generated in 9.10 seconds (21.97 tokens/s, 200 tokens)
```

4-bit quantized model:
```
Loading OPT-2.7B-Erebus...
Loading model ...
Done.
Loaded the model in 1.00 seconds.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Output generated in 57.77 seconds (3.46 tokens/s, 200 tokens)
```

You can notice huge 5x performance drop. 
Do you have any ideas what might be causing it?

**Comment by qwopqwop200** [comment]
It's slightly slower than fp16 on OPT, but not as extreme as 5x.
OPT-2.7B 4bit
Median: 0.03400063514709473
OPT-2.7B FP16
Median: 0.026999950408935547
And it seems related to the problem(https://github.com/qwopqwop200/GPTQ-for-LLaMa/issues/30).
It's a personal opinion, but it seems that there is a possibility that there is a problem with text-generation-webui.

**Comment by qwopqwop200** [comment]
Basically, opt and LLaMa have little difference in implementation. So it behaves almost the same.
Please raise the issue here(https://github.com/qwopqwop200/GPTQ-for-LLaMa/issues/30).
