### ISSUE TITLE
Issue loading tokenizer when using local models

### ISSUE THREAD

**Issue by iamlemec** [qwopqwop200/GPTQ-for-LLaMa#65]
Thanks for this wonderful project! When loading from a local model (converted using `convert_llama_weights_to_hf.py`), both the quantization and inference routines can't find the tokenizer because it's in the `tokenizer` directory rather than the `llama-*` directory, which is what gets passed to `AutoTokenizer`.

A successful workaround is to either add an another `tokenizer` command-line argument (as I've done [here](https://github.com/iamlemec/GPTQ-for-LLaMa)) or to copy/link the tokenizer files into each model directory. Might be worth adding something to the README at least.

Also, unrelated: the call to `load_quant` on `llama_inference.py:112` is missing the `groupsize` argument.

**Comment by qwopqwop200** [comment]
Modified convert_llama_weights_to_hf code so that tokenizers are created in llama-*. And bug fixes.
