### ISSUE TITLE
Is compute time expected to go up linearly with batch size?

### ISSUE THREAD

**Issue by zphang** [qwopqwop200/GPTQ-for-LLaMa#66]
From a quick test, I noticed that the 4-bit code gets linearly slowly as I increase the batch size:

- bs=1: 1.97 s
- bs=8: 15.5 s
- bs=64: 127s s

From a quick, uninformed skim on the cuda code, it looks like it's looping over blocks, in which case it seems pretty reasonable (and unfortunate) that it'd be scaling linearly. Is there room for optimization there to compute blocks in parallel?

**Comment by qwopqwop200** [comment]
A linear increase with batchsize is normal. Further optimization seems very difficult.
