### ISSUE TITLE
TypeError: load_quant() missing 1 required positional argument: 'groupsize'

### ISSUE THREAD

**Issue by matbee-eth** [qwopqwop200/GPTQ-for-LLaMa#69]
Using latest `main`
```
(textgen) acidhax@PC:~/text-generation-webui$ python server.py --listen --auto-devices --model llama-13b-hf --gptq-bits 4
Loading llama-13b-hf...
Traceback (most recent call last):
  File "/home/acidhax/text-generation-webui/server.py", line 242, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/acidhax/text-generation-webui/modules/models.py", line 101, in load_model
    model = load_quantized(model_name)
  File "/home/acidhax/text-generation-webui/modules/GPTQ_loader.py", line 55, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.gptq_bits)
TypeError: load_quant() missing 1 required positional argument: 'groupsize'
```

**Comment by qwopqwop200** [comment]
It looks like text-generation-webui is causing a problem.
Try fixing it like this:
`
groupsize = -1
model = load_quant(str(path_to_model), str(pt_path), shared.args.gptq_bits, groupsize)
`

**Comment by allenhs** [comment]
I apply the fix but then I get a bunch of errors like this one:         size mismatch for model.layers.59.mlp.up_proj.scales: copying a param with shape torch.Size([17920, 1]) from checkpoint, the shape in current model is torch.Size([1, 17920]).

**Comment by qwopqwop200** [comment]
The code has changed due to current grouping support. please quantization the LLaMa model once again.

**Comment by allenhs** [comment]
Ah ok, I figured that might be the answer.

**Comment by johnwayne087** [comment]
I have converted the 30B model to HF with the latest script, and quantized with the latest repo. I am still getting that initial error from the top of this issue.

**Comment by zaziki23** [comment]
same issue for me, converted with latest code and i get the same error
