### ISSUE TITLE
error on amd gpu when starting setup_cuda

### ISSUE THREAD

**Issue by maxime-fleury** [qwopqwop200/GPTQ-for-LLaMa#72]
Hello, any one knows what's wrong with this ?
`PS C:\Users\Max\llama\repositories\GPTQ-for-LLaMa> conda info

     active environment : None
       user config file : C:\Users\Max\.condarc
 populated config files :
          conda version : 4.14.0
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\ProgramData\Miniconda3V  (writable)
      conda av data dir : C:\ProgramData\Miniconda3V\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Miniconda3V\pkgs
                          C:\Users\Max\.conda\pkgs
                          C:\Users\Max\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Miniconda3V\envs
                          C:\Users\Max\.conda\envs
                          C:\Users\Max\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.14.0 requests/2.28.1 CPython/3.9.5 Windows/10 Windows/10.0.22624
          administrator : True
             netrc file : None
           offline mode : False

PS C:\Users\Max\llama\repositories\GPTQ-for-LLaMa> pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/rocm5.2
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/rocm5.2
Requirement already satisfied: torch in c:\programdata\miniconda3v\lib\site-packages (2.0.0)
Requirement already satisfied: torchvision in c:\programdata\miniconda3v\lib\site-packages (0.15.1)
Requirement already satisfied: torchaudio in c:\programdata\miniconda3v\lib\site-packages (2.0.1)
Requirement already satisfied: jinja2 in c:\programdata\miniconda3v\lib\site-packages (from torch) (3.1.2)
Requirement already satisfied: networkx in c:\programdata\miniconda3v\lib\site-packages (from torch) (3.0)
Requirement already satisfied: sympy in c:\programdata\miniconda3v\lib\site-packages (from torch) (1.11.1)
Requirement already satisfied: typing-extensions in c:\programdata\miniconda3v\lib\site-packages (from torch) (4.4.0)
Requirement already satisfied: filelock in c:\programdata\miniconda3v\lib\site-packages (from torch) (3.8.0)
Requirement already satisfied: requests in c:\programdata\miniconda3v\lib\site-packages (from torchvision) (2.28.1)
Requirement already satisfied: numpy in c:\programdata\miniconda3v\lib\site-packages (from torchvision) (1.24.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\programdata\miniconda3v\lib\site-packages (from torchvision) (9.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\miniconda3v\lib\site-packages (from jinja2->torch) (2.1.2)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\programdata\miniconda3v\lib\site-packages (from requests->torchvision) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\miniconda3v\lib\site-packages (from requests->torchvision) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\miniconda3v\lib\site-packages (from requests->torchvision) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\programdata\miniconda3v\lib\site-packages (from requests->torchvision) (1.26.14)
Requirement already satisfied: mpmath>=0.19 in c:\programdata\miniconda3v\lib\site-packages (from sympy->torch) (1.3.0)
PS C:\Users\Max\llama\repositories\GPTQ-for-LLaMa> python setup_cuda.py install
Traceback (most recent call last):
  File "C:\Users\Max\llama\repositories\GPTQ-for-LLaMa\setup_cuda.py", line 6, in <module>
    ext_modules=[cpp_extension.CUDAExtension(
  File "C:\ProgramData\Miniconda3V\lib\site-packages\torch\utils\cpp_extension.py", line 1048, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "C:\ProgramData\Miniconda3V\lib\site-packages\torch\utils\cpp_extension.py", line 1186, in library_paths
    paths.append(_join_cuda_home(lib_dir))
  File "C:\ProgramData\Miniconda3V\lib\site-packages\torch\utils\cpp_extension.py", line 2223, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
PS C:\Users\Max\llama\repositories\GPTQ-for-LLaMa>`

I followed this site intructions: 
https://aituts.com/llama/

also this folder is empty:  miniconda3V\envs\textgen\

**Comment by qwopqwop200** [comment]
Since i have changed to use triton now, i do not have this issue.
