### ISSUE TITLE
Inference using CPU

### ISSUE THREAD

**Issue by lodorg** [qwopqwop200/GPTQ-for-LLaMa#73]
Hi, I'm interested to run LLAMA 4bit GPTQ, but I don't have a GPU. Is it possible to run this model on CPU only?

**Comment by aljungberg** [comment]
I don't think so since the matrix multiplication is implemented in CUDA. You'd probably need to reimplement `vecquant4matmul` in CPP if you wanted to go down this path.

**Comment by green-s** [comment]
In the mean time you can use [llama.cpp](https://github.com/ggerganov/llama.cpp), which now has a [script](https://github.com/ggerganov/llama.cpp/blob/master/convert-gptq-to-ggml.py) to convert GPTQ models.

**Comment by qwopqwop200** [comment]
Please use [LLama.cpp](https://github.com/ggerganov/llama.cpp)
