### ISSUE TITLE
Inference with 4bit is slow than fp32

### ISSUE THREAD

**Issue by heya5** [qwopqwop200/GPTQ-for-LLaMa#77]
My environment:
- GPU: RTX 3090
- torch 1.12.0+cu116
- transformers 4.21.1

**Comment by diegomontoya** [comment]
@heya5 Your setup isn't even capable running llama models. Transformers version you have doesn't come with the llama decoder classes. First, how are you even running this repo code? Second, try upgrading your drivers, cuda, and torch to 2.0 stable.

**Comment by heya5** [comment]
My bad. I directly import LLaMAForCausalLM from the dev branch before it merged to the main branch. I will try the latest version of torch and transformers. Thanks for your reply!
