### ISSUE TITLE
How to use for inference?

### ISSUE THREAD

**Issue by DanielWe2** [qwopqwop200/GPTQ-for-LLaMa#8]
I could the model compression running and the benchmark also works.

But how would I use the model for inference? It there any example? The standard things from transformers are not working with "Only supports a single token currently." That seems related to #6.

**Comment by ItsLogic** [comment]
It actually does work with standard transformers inference code but the kernel is limiting the input to 1 token. If you run inference with a word/letter that only counts as 1 token it will run to completion as shown below with the word "ball" which is a single token.
![image](https://user-images.githubusercontent.com/38233332/223903387-d985ee1f-74ec-4ac7-ac0d-0cec1e897a16.png)
The kernel needs to be updated before inference can work with multiple tokens so we need to wait on #6 to be solved before its usable

**Comment by MarkSchmidty** [comment]
I don't have time to test, but if you clone https://github.com/qwopqwop200/GPTQ-for-LLaMa/pull/9 you may be able to use more than one input token. At least that's what the PR says.

**Comment by qwopqwop200** [comment]
Implemented batch processing of cuda kernel.

**Comment by qwopqwop200** [comment]
Added simple inference code.
`CUDA_VISIBLE_DEVICES=0 python llama_inference.py decapoda-research/llama-7b-hf --wbits 4 --load llama7b-4bit.pt --text "this is llama"
`
