### ISSUE TITLE
args is not defined after adding faster_kernel

### ISSUE THREAD

**Issue by ye7iaserag** [qwopqwop200/GPTQ-for-LLaMa#80]
After [514136fb2ce07efbdcb528a7ff18821660155725](https://github.com/qwopqwop200/GPTQ-for-LLaMa/tree/514136fb2ce07efbdcb528a7ff18821660155725)

```
   File "/app/repositories/GPTQ-for-LLaMa/llama.py", line 252, in load_quant
     make_quant(model, layers, wbits, groupsize, faster=args.faster_kernel)
 NameError: name 'args' is not defined
```

**Comment by EyeDeck** [comment]
Yeah, small oversight there.
https://github.com/oobabooga/text-generation-webui/pull/530#issuecomment-1483906377
https://github.com/qwopqwop200/GPTQ-for-LLaMa/commit/514136fb2ce07efbdcb528a7ff18821660155725

`args` doesn't get defined unless llama.py is executed directly, so calling the functions in llama.py externally (like text-generation-webui does) crashes when it gets there.
I guess you could technically do, like, `faster=("args" in globals() and args.faster_kernel)` as a bandaid.

**Comment by qwopqwop200** [comment]
probably fixed it.
