### ISSUE TITLE
Windows 11 / WSL2 / Ubuntu / cuda 11.7 / RTX 3070 - IndexError: list index out of range (+PTX)

### ISSUE THREAD

**Issue by glarsson** [qwopqwop200/GPTQ-for-LLaMa#85]
Hi,

I just had the worst time trying to compile this under Ubuntu WSL2 in Windows 11 on CUDA 11.7.  
```
...line 1773, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range
```
After following all kinds of documentation here and on oobaboogas webui wiki/issues list, and google, trying everything I could think of to compile this thing after this error above, what finally worked was manually setting the environment variable (see https://en.m.wikipedia.org/wiki/CUDA#GPUs_supported):
```
TORCH_CUDA_ARCH_LIST=8.6
```
In conda this can be done like this: conda env config vars set `TORCH_CUDA_ARCH_LIST=8.6` and then `conda activate textgen` (or whatever you called your environment, I skipped creating a separate for just GPTQ.

I had _LOTS_ of other problems too with version inconsistencies etc which were solved by removing everything cuda and then installing this EXACT package: https://developer.nvidia.com/cuda-11-7-0-download-archive?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=runfile_local
```
wget https://developer.download.nvidia.com/compute/cuda/11.7.0/local_installers/cuda_11.7.0_515.43.04_linux.run
sudo sh cuda_11.7.0_515.43.04_linux.run
```
DO NOT SELECT DRIVER IF YOU ARE ON WSL! The driver is injected from Windows, do not install GPU driver on WSL.

Make sure symlinks look good in /usr/local:
```
(textgen) gerry@***:~/text-generation-webui/repositories/GPTQ-for-LLaMa$ ls -la /usr/local
total 0
drwxr-xr-x 1 root root 4096 Mar 26 22:43 .
drwxr-xr-x 1 root root 4096 Jan  3 22:40 ..
lrwxrwxrwx 1 root root   21 Mar 26 22:43 cuda -> /usr/local/cuda-11.7/
drwxr-xr-x 1 root root 4096 Mar 26 22:45 cuda-11.7
drwxr-xr-x 1 root root 4096 Jan  3 22:40 etc
drwxr-xr-x 1 root root 4096 Jan  3 22:40 games
drwxr-xr-x 1 root root 4096 Jan  3 22:40 include
drwxr-xr-x 1 root root 4096 Jan  3 22:40 lib
lrwxrwxrwx 1 root root    9 Jan  3 22:40 man -> share/man
drwxr-xr-x 1 root root 4096 Jan  3 22:40 sbin
drwxr-xr-x 1 root root 4096 Mar 26 21:37 share
drwxr-xr-x 1 root root 4096 Jan  3 22:40 src
(textgen) gerry@***:~/text-generation-webui/repositories/GPTQ-for-LLaMa$
```
Hopefully this will save someone some time.

--

So just a quick comment here, I ... Well, I was running WSL1 :) Maybe that had something to do with it! Because it couldn't find the GPU, so I recompiled the kernel and tried to pass it through .wslconfig and it didn't take. wsl --status gave me the deets. Did a `wsl --set-version Ubuntu 2` and that sorted out the GPU problem - and potentially the above problem too, without having to inject the variable. Ah well, I'm too tired to check now, I will leave this here anyways if that's OK.

**Comment by qwopqwop200** [comment]
Changed to use Triton instead of CUDA now. It seems that this problem won't happen.
