### ISSUE TITLE
high VRAM Memory Allocation while evaluation

### ISSUE THREAD

**Issue by zaziki23** [qwopqwop200/GPTQ-for-LLaMa#86]
[log.txt](https://github.com/qwopqwop200/GPTQ-for-LLaMa/files/11074545/log.txt)

I'm trying to quantize the 13B model, but it seems that 12GB VRAM is not enough for this. Can this maybe someome confirm?
Is there any possibility to reduce the amount of ram or use smaller batches?
I did the 7B before, which passed. So in genereal it seems to work.

**Comment by EyeDeck** [comment]
Yeah, it can do that.

If you just want the end result and don't need to see perplexity scores, you can just cut/comment out the block of code that follows here: https://github.com/qwopqwop200/GPTQ-for-LLaMa/blob/da847d1a1267e837dd222b072e86dae987df6e69/llama.py#L464

Or you can move the `if args.save:` and `if args.save_safetensors:` blocks above the evaluation block, so it saves before (maybe) crashing. I've had to do that while experimenting with some models that just don't want to cooperate.

**Comment by diegomontoya** [comment]
This just happened to me. vram oom. 2+ hours wasted.

Anyways, I made sure it won't happen to anyone else again. 

https://github.com/qwopqwop200/GPTQ-for-LLaMa/commit/4710229c705f509ce48845ace561a3b8efe7ffb5

**Comment by qwopqwop200** [comment]
This problem is solved.
