### ISSUE TITLE
Error while python setup_cuda.py install> 

### ISSUE THREAD

**Issue by mahxds** [qwopqwop200/GPTQ-for-LLaMa#88]
Hi everyone,

I got following setup

Ubuntu VM
Tesla M40 24GB passed through ( correctly passed through to vm)
62GB RAM
200 GB vdisk

everything work fine, installting 8 bit and using works fine. 
But while installing 4bit i get and error during <python setup_cuda.py install>

I get compiling errors with quant cuda. 
quant_cuda_kernel.cu error: identifier "__hfma2" is undefined

 Anyone experienced same ?

**Comment by timofeev1995** [comment]
Same thing for me at the last commit.

**Comment by diegomontoya** [comment]
@mahxds  @timofeev1995  Your Nvidia needs to support the HFMA2 instruction set. I think the M40 is too old and missing this instruction.

**Comment by diegomontoya** [comment]
A potential work around is to checkout the repo before the "faster" kernel code was merged in. 

Try checking out this commit: https://github.com/qwopqwop200/GPTQ-for-LLaMa/commit/841feedde876785bc8022ca48fd9c3ff626587e2

**Comment by Kadah** [comment]
Was getting this too. In my case I have both Maxwell and Pascal Tesla cards in my server. Doing `CUDA_VISIBLE_DEVICES=1,2 python setup_cuda.py install` to select only the P40 cards worked.

**Comment by timofeev1995** [comment]
I face that kind of issue with a100/3090. 
Thank you for advices to check out https://github.com/qwopqwop200/GPTQ-for-LLaMa/commit/841feedde876785bc8022ca48fd9c3ff626587e2 commit. I'll try :)

**Comment by diegomontoya** [comment]
@timofeev1995 You should not have this issue with a100/3090. This is for pre-pascal gpus like Tesla M40. If you get this error, you probably have broken or a very old cuda that predates your gpu.

**Comment by timofeev1995** [comment]
I understand that, but have no idea why this is happening. 
I have successfully built the code using the commit above.

```
(gptq) nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
(gptq) nvidia-smi
Tue Mar 28 09:32:16 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.73.05    Driver Version: 510.73.05    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
...
```

**Comment by diegomontoya** [comment]
@timofeev1995  You most likely have conflict of multiple nvcc libraries installed the compiler chose the very old version. Best to test all the models in a container, separate from host os since you will be updating libraries quite a bit due to fast pace of dev.  Create a clean 22.04 env container, install miniconda (or conda) and do the pip install requirements.

**Comment by timofeev1995** [comment]
It is a container (but actually the 22.10 one). I'll try to figure out what was the problem actually.
Very appreciated for your time to solve the issue, and for the library itself. Thank you!

**Comment by Titaniumtown** [comment]
I also experience a similar issue with my rx 6900xt. Hope a solution is found to support hardware that doesn't support some extensions!

**Comment by qwopqwop200** [comment]
currently using triton, so I don't think this problem will occur.

**Comment by danmincu** [comment]
same boat M40 with Ubuntu. Please report back did anoyone got lucky with a previous commit? 
Edit: confirming that the commit above actually works allowing to compile LLaMa for the M40

**Comment by BretG137** [comment]
> same boat M40 with Ubuntu. Please report back did anoyone got lucky with a previous commit? Edit: confirming that the commit above actually works allowing to compile LLaMa for the M40

Thanks!
git checkout 841feed
worked with my tesla m40 as well.

**Comment by TheBestIsComing** [comment]
I am new to this forum and my programming experience is rather limited. Currently, I'm finding it challenging to comprehend the codebase for Llama.

I recently purchased an Nvidia M40 and I've successfully managed to get nvidia-smi working on Docker in an Ubuntu environment. Additionally, I've been able to operate the M40 on my Windows machine, even managing to play games on the device, which has been quite exciting!

However, my primary intent behind acquiring the M40 is to run language models from HuggingFace on it, a goal I am yet to realize. Despite numerous attempts, I have been unable to get it working on either Ubuntu or Windows.

I've identified the commit 841feed as potentially relevant to my issue. However, my lack of experience makes it hard to discern if this is indeed the solution. Could anyone please provide some guidance on how to proceed? Specifically, I'm wondering whether there is a need to manually modify something in the code.

Any help on this would be greatly appreciated. Thank you in advance for your assistance and patience.
