### ISSUE TITLE
Support for corrected Llama

### ISSUE THREAD

**Issue by gante** [qwopqwop200/GPTQ-for-LLaMa#89]
Hey GPTQ-for-LlaMa maintainers 👋  @qwopqwop200 @MasterTaffer 

I'm a maintainer from HuggingFace 🤗 , responsible for text generation. Llama was not compatible with left-padding, which is required for batched generation, so a fix was applied (https://github.com/huggingface/transformers/pull/22382). This added a new non-optional input in the inner layers, which breaks your code (see [this issue](https://github.com/huggingface/transformers/issues/22407)).

I believe that potential fixes include:
1. Catching `position_ids` [here](https://github.com/qwopqwop200/GPTQ-for-LLaMa/blob/main/llama.py#L48), setting it [here](https://github.com/qwopqwop200/GPTQ-for-LLaMa/blob/9fe88b988481daf69c518873f617902bde8b7bcc/llama.py#L64), and passing it to the `layer()` calls;
2. Pinning `transformers` to a version prior to this commit, e.g. `5506d0496957cde19318eee3d34ee682b654abe8` (the commit immediately before)

Cheers!

**Comment by qwopqwop200** [comment]
Modified the current code to support.

**Comment by kpoeppel** [comment]
This was still an issue for me and the suggested changes by @gante worked for me. So I suggest to re-open the issue. Thanks for the great repo!

Edit: It's resolved now. Thanks.
