### ISSUE TITLE
8-bit quantization succeeds with great benchmarks, but inference produces garbage past 128 tokens

### ISSUE THREAD

**Issue by QM60** [qwopqwop200/GPTQ-for-LLaMa#91]
Quantized with
`python llama.py llama-13b c4 --wbits 8 --true-sequential --groupsize 128 --save_safetensors llama-13b-8bit-128g.safetensors`

Benchmarks looked great as expected, this should be severe overkill and it appeared to be so
`wikitext2: 5.091(vs 5.08) PTB: 8.06(vs 8.06) C4: 6.61(vs 6.58)`

However upon loading and trying to do inference, the model produces nothing but gibberish once it goes past the 128 token limit (probably related to the new optimization?).
Example (prompt is up to the first "Question:")

> Common sense questions and answers
> 
> Question: What is the difference between a "common sense" question and an ordinary question?
> 
> Answer: The common-sense question has been asked many times before, but not answered to anyone's satisfaction.  It is usually asked by someone who does not have much experience with the subject at hand, so it may be naive or even silly.  An ordinary question is one that has already been asked and answered satisfactorily in the past; if you are asking such a question, you should search for previous threads on the topic first, rather than starting a new thread of your own.,..,.,,,,..,,.,.,,.,........,,,....,,,... together.,,....,.,...,,,,..,.....,.....,,...,.,.,,..,..,.,,,,,,.,..,,.,..,,..,.,.,....,.

**Comment by qwopqwop200** [comment]
fix  it

**Comment by QM60** [comment]
It seems to still be broken. I thought the fix might require re-quantizing but after another pass I got the same issues. Using cuda branch.
`python llama.py H:\Downloads\LLaMA-HFv2\llama-13b c4 --wbits 8 --true-sequential --groupsize 128 --save_safetensors llama-13b-8bit-128g.safetensors`
appears to successfully quantize, but then
`python llama.py H:\Downloads\LLaMA-HFv2\llama-13b c4 --load llama-13b-8bit-128g.safetensors --wbits 8 --true-sequential --groupsize 128 --eval`
gives a perplexity of "9590.99609375" for wikitext2. I wonder if something breaks during save/load.
