### ISSUE TITLE
Name format mixup - LLaMA has a capital A

### ISSUE THREAD

**Issue by mcmonkey4eva** [qwopqwop200/GPTQ-for-LLaMa#92]
This is really minor but - This repo is full of `LLaMa` but it's actually written as `LLaMA` with a capital A on the end. You can see this in the arxiv https://arxiv.org/abs/2302.13971

(As best I can tell, `LLaMA` is short for `Large Language Model Meta AI` and that A in the middle is lowercase because there's no reason for it to be there other than making the acronym sound nice)

**Comment by qwopqwop200** [comment]
I only realized this now. fixed a typo.
