### ISSUE TITLE
Use multiple gpu for quantization?

### ISSUE THREAD

**Issue by sgsdxzy** [qwopqwop200/GPTQ-for-LLaMa#94]
It seems to only use 1 gpu for now, making quantizing large models very time-consuming, even if multiple gpus are present.
Is it possible to quantizing multiple layers at the same time, or is it must be done in sequence because latter layers depend on former layers (I don't know how GPTQ works)?
If parallel quantization is supported, I can put my 4 gpus to good work and experiment with more settings.

**Comment by qwopqwop200** [comment]
https://github.com/qwopqwop200/GPTQ-for-LLaMa/blob/triton/llama.py#L120
Looking at this line, we can see that it depends on the previous layer.
