### ISSUE TITLE
KeyError on conversion attempt.

### ISSUE THREAD

**Issue by GamerUntouch** [qwopqwop200/GPTQ-for-LLaMa#97]
I'm trying to convert a 30B model from int8 HF format to 4bit.
When doing so, I get this error.

 File "/workspace/GPTQ-for-LLaMa/llama.py", line 49, in forward
    cache['position_ids'] = kwargs['position_ids']
KeyError: 'position_ids'

What is causing this? This was a model converted with the HF model converted and then merged with a LoRA. I didn't convert it with the script provided.

**Comment by USBhost** [comment]
I second this.

**Comment by qwopqwop200** [comment]
https://github.com/qwopqwop200/GPTQ-for-LLaMa/issues/95

**Comment by USBhost** [comment]
That did it thanks.

**Comment by GamerUntouch** [comment]
Fixed for me too.
