### ISSUE TITLE
AMD Installation broke about 1 week ago 

### ISSUE THREAD

**Issue by YellowRoseCx** [qwopqwop200/GPTQ-for-LLaMa#98]
I use a AMD rx 6800xt on Linux with ROCM

I've been successfully using your program for a week with fast inference speed

Your software setup_cuda worked for me up through this commit: https://github.com/qwopqwop200/GPTQ-for-LLaMa/commit/841feedde876785bc8022ca48fd9c3ff626587e2
after that it doesnt' work for me

The Pytorch version "works" but its speed is 0.78 tokens per second instead of 10-18 tokens per second.

The latest version that you've called CUDA gives me these errors while installing:

```
(koboldai-rocm) yellowrose@yellowrose-ws-linux:/mnt/UbuntuData/AI/GPTQ-for-LLaMa$ python setup_cuda.py install
/mnt/UbuntuData/AI/GPTQ-for-LLaMa/quant_cuda.cpp -> /mnt/UbuntuData/AI/GPTQ-for-LLaMa/quant_hip.cpp [ok]
/mnt/UbuntuData/AI/GPTQ-for-LLaMa/quant_cuda_kernel.cu -> /mnt/UbuntuData/AI/GPTQ-for-LLaMa/quant_hip_kernel.hip [ok]
Successfully preprocessed all matching files.
Total number of unsupported CUDA function calls: 0


Total number of replaced kernel launches: 7
running install
/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
creating quant_cuda.egg-info
writing quant_cuda.egg-info/PKG-INFO
writing dependency_links to quant_cuda.egg-info/dependency_links.txt
writing top-level names to quant_cuda.egg-info/top_level.txt
writing manifest file 'quant_cuda.egg-info/SOURCES.txt'
reading manifest file 'quant_cuda.egg-info/SOURCES.txt'
writing manifest file 'quant_cuda.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'quant_cuda' extension
creating /mnt/UbuntuData/AI/GPTQ-for-LLaMa/build
creating /mnt/UbuntuData/AI/GPTQ-for-LLaMa/build/temp.linux-x86_64-cpython-38
Emitting ninja build file /mnt/UbuntuData/AI/GPTQ-for-LLaMa/build/temp.linux-x86_64-cpython-38/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] /opt/rocm-5.4.3/bin/hipcc  -I/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/include -I/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/include/TH -I/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/include/THC -I/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/include/THH -I/opt/rocm-5.4.3/include -I/opt/rocm-5.4.3/miopen/include -I/opt/rocm-5.4.3/hip/include -I/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/include/python3.8 -c -c /mnt/UbuntuData/AI/GPTQ-for-LLaMa/quant_hip_kernel.hip -o /mnt/UbuntuData/AI/GPTQ-for-LLaMa/build/temp.linux-x86_64-cpython-38/quant_hip_kernel.o -fPIC -D__HIP_PLATFORM_HCC__=1 -DUSE_ROCM=1 -DCUDA_HAS_FP16=1 -D__HIP_NO_HALF_OPERATORS__=1 -D__HIP_NO_HALF_CONVERSIONS__=1 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=quant_cuda -D_GLIBCXX_USE_CXX11_ABI=0 --amdgpu-target=gfx900 --amdgpu-target=gfx906 --amdgpu-target=gfx908 --amdgpu-target=gfx90a --amdgpu-target=gfx1030 -fno-gpu-rdc -std=c++17
FAILED: /mnt/UbuntuData/AI/GPTQ-for-LLaMa/build/temp.linux-x86_64-cpython-38/quant_hip_kernel.o 
/opt/rocm-5.4.3/bin/hipcc  -I/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/include -I/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/include/TH -I/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/include/THC -I/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/include/THH -I/opt/rocm-5.4.3/include -I/opt/rocm-5.4.3/miopen/include -I/opt/rocm-5.4.3/hip/include -I/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/include/python3.8 -c -c /mnt/UbuntuData/AI/GPTQ-for-LLaMa/quant_hip_kernel.hip -o /mnt/UbuntuData/AI/GPTQ-for-LLaMa/build/temp.linux-x86_64-cpython-38/quant_hip_kernel.o -fPIC -D__HIP_PLATFORM_HCC__=1 -DUSE_ROCM=1 -DCUDA_HAS_FP16=1 -D__HIP_NO_HALF_OPERATORS__=1 -D__HIP_NO_HALF_CONVERSIONS__=1 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=quant_cuda -D_GLIBCXX_USE_CXX11_ABI=0 --amdgpu-target=gfx900 --amdgpu-target=gfx906 --amdgpu-target=gfx908 --amdgpu-target=gfx90a --amdgpu-target=gfx1030 -fno-gpu-rdc -std=c++17
Warning: The --amdgpu-target option has been deprecated and will be removed in the future.  Use --offload-arch instead.
Warning: The --amdgpu-target option has been deprecated and will be removed in the future.  Use --offload-arch instead.
Warning: The --amdgpu-target option has been deprecated and will be removed in the future.  Use --offload-arch instead.
Warning: The --amdgpu-target option has been deprecated and will be removed in the future.  Use --offload-arch instead.
Warning: The --amdgpu-target option has been deprecated and will be removed in the future.  Use --offload-arch instead.
In file included from /mnt/UbuntuData/AI/GPTQ-for-LLaMa/quant_hip_kernel.hip:2:
In file included from /mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7:
In file included from /mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3:
In file included from /mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/autograd.h:3:
In file included from /mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/variable.h:6:
In file included from /mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2:
In file included from /mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/function_hook.h:3:
In file included from /mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/include/ATen/Tensor.h:3:
In file included from /mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/include/ATen/core/Tensor.h:3:
In file included from /mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:11:
In file included from /mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/include/c10/core/Device.h:3:
In file included from /mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/include/c10/core/DeviceType.h:8:
In file included from /mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/include/c10/macros/Macros.h:247:
/opt/rocm-5.4.3/hip/include/hip/hip_runtime.h:25:9: warning: This file is deprecated. Use header files from HIP_PATH/include, where HIP_PATH corresponds to HIP install path [-W#pragma-messages]
#pragma message("This file is deprecated. Use header files from HIP_PATH/include, where HIP_PATH corresponds to HIP install path")
```

.......................................................

```
  File "/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/setuptools/dist.py", line 1221, in run_command
    super().run_command(command)
  File "/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
    build_ext.build_extensions(self)
  File "/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/runtime/envs/koboldai-rocm/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
(koboldai-rocm) yellowrose@yellowrose-ws-linux:/mnt/UbuntuData/AI/GPTQ-for-LLaMa$ 

```

        Full Error Log here: https://pastebin.com/vh5PG4V6

**Comment by arctic-marmoset** [comment]
I ran into this issue too a few days ago. This is due to the `faster` kernel functions, which make use of half2 types. HIP doesn't seem to support them fully, at least not in this use case. I haven't looked into it further, so I'm not sure if it goes deeper (i.e. if there's anything that isn't supported by hardware). A workaround is to comment those functions out.

**Comment by YellowRoseCx** [comment]
> 

Amazing, thank you! That made it work perfectly

If anyone else wants to use it, here are my changes for AMD: https://github.com/YellowRoseCx/GPTQ-for-LLaMa-AMD

**Comment by arctic-marmoset** [comment]
Glad I could help. Ideally we should bring this up with the HIP maintainers for clarification, but I haven't had the chance to submit an issue with them yet.

**Comment by YellowRoseCx** [comment]
> Glad I could help. Ideally we should bring this up with the HIP maintainers for clarification, but I haven't had the chance to submit an issue with them yet.

It installed as quant-cuda, but when trying to load it, I'm getting 

Traceback (most recent call last):
  File "aiserver.py", line 91, in <module>
    from repos.gptq.gptq import *
  File "/mnt/UbuntuData/AI/KoboldAI4bit/KoboldAI/repos/gptq/gptq.py", line 8, in <module>
    from quant import *
ModuleNotFoundError: No module named 'quant'

**Comment by YellowRoseCx** [comment]
I fixed it, I forgot to close a comment at the end of a file

Thanks again!

**Comment by arctic-marmoset** [comment]
I took another look at the issue, and it turns out the kernel source code relies on being able to implicitly cast from `unsigned short` to `half`. However, pytorch adds two defines that change this behaviour for HIP: `__HIP_NO_HALF_CONVERSIONS__` and
`__HIP_NO_HALF_OPERATORS__`. I don't know the reason for the defines. Adding additional compile args in the CUDAExtension to undef them resolves this.

There's also an  issue with `half2` variables not being able to be initialised with empty braces `{}` unless it's on the same line as the declaration. The compiler isn't able to resolve the right constructor for some reason (it complains about assigning `void` to `half2`). A simple workaround is to explicitly specify `half2` with the braces: `half2{}`.

I've made these changes in a fork [here](https://github.com/arctic-marmoset/GPTQ-for-LLaMa/tree/hip), in case anyone is interested.

**Comment by WapaMario63** [comment]
I made my own fork and what I did was use the`__half22float2()` function instead of the original `__half2float()`, to get around the implicit cast. That half2 variable workaround is much simpler than my overthinking of using: `std::memset(&res2, 0, sizeof(half2));` due to using it in recent personal unrelated projects.

https://github.com/WapaMario63/GPTQ-for-LLaMa-ROCm

**Comment by qwopqwop200** [comment]
I don't currently use half, so I don't think there will be any problems.

**Comment by regstuff** [comment]
> I made my own fork and what I did was use the`__half22float2()` function instead of the original `__half2float()`, to get around the implicit cast. That half2 variable workaround is much simpler than my overthinking of using: `std::memset(&res2, 0, sizeof(half2));` due to using it in recent personal unrelated projects.
> 
> https://github.com/WapaMario63/GPTQ-for-LLaMa-ROCm

Hi. Tried using your branch rocm-latest but ended up with a error: `RuntimeError: Error(s) in loading state_dict for LlamaForCausalLM:
        Missing key(s) in state_dict`
Was trying to run this model: https://huggingface.co/anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g
I get the same error with qwop's repo as well.

**Comment by WapaMario63** [comment]
> > I made my own fork and what I did was use the`__half22float2()` function instead of the original `__half2float()`, to get around the implicit cast. That half2 variable workaround is much simpler than my overthinking of using: `std::memset(&res2, 0, sizeof(half2));` due to using it in recent personal unrelated projects.
> > https://github.com/WapaMario63/GPTQ-for-LLaMa-ROCm
> 
> Hi. Tried using your branch rocm-latest but ended up with a error: `RuntimeError: Error(s) in loading state_dict for LlamaForCausalLM: Missing key(s) in state_dict` Was trying to run this model: https://huggingface.co/anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g I get the same error with qwop's repo as well.

Being honest, I have not tested that branch at all with any model and it was simply made to just keep up with every change on qwop's cuda branch, but with the kernel at least running on HIP.  I'm just waiting to see a model that requires that cuda branch to test it on with ooba's textgen. In the case of that model you linked, the cuda version works with the base rocm branch just fine as I just tried it out.

**Comment by regstuff** [comment]
> Being honest, I have not tested that branch at all with any model and it was simply made to just keep up with every change on qwop's cuda branch, but with the kernel at least running on HIP. I'm just waiting to see a model that requires that cuda branch to test it on with ooba's textgen. In the case of that model you linked, the cuda version works with the base rocm branch just fine as I just tried it out.

Could you share the command you're using to run the model. Maybe I'm messing up with the flags somewhere?

**Comment by WapaMario63** [comment]
> > Being honest, I have not tested that branch at all with any model and it was simply made to just keep up with every change on qwop's cuda branch, but with the kernel at least running on HIP. I'm just waiting to see a model that requires that cuda branch to test it on with ooba's textgen. In the case of that model you linked, the cuda version works with the base rocm branch just fine as I just tried it out.
> 
> Could you share the command you're using to run the model. Maybe I'm messing up with the flags somewhere?

Its the same as with any other 4bit model loaded with [ooba's textgen](https://github.com/oobabooga/text-generation-webui), which is:
`python server.py --model gpt4-x-alpaca-13b-native-4bit-128g --wbits 4 --groupsize 128`
The model name corresponds to the folder name where the model resides, in textgen's models folder. That folder should have everything inside the [model's repo](https://huggingface.co/anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g/tree/main), except the ggml model folder and what I believe to be crucial, to **not** have both .pt models, you only need the one ending in cuda. If that doesn't work, try renaming the model folder itself to start with "alpaca" instead, since I remember seeing code that looks for the first word of the model folder to match if its llama, alpaca, opt and whatever other supported model. I renamed it just to make it a bit shorter and have it start with alpaca for consistency, so who knows if that has to do with getting it to run.
